"""Gold seed catalog — FreeMarker (Stage 2). 50 manually-authored GoldSeedExample dicts."""

FREEMARKER_SEEDS: list[dict] = [
    {
        "id": "seed-fmt-001",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders an unordered list from a sequence `items` of strings. Escape each item for HTML output. When `items` is missing or empty, render a paragraph saying no items were found.",
        "code": "<#-- Model: items: sequence of strings -->\n<#if !items?has_content>\n  <p>No items were found.</p>\n<#else>\n  <ul>\n    <#list items as item>\n      <li>${item?html}</li>\n    </#list>\n  </ul>\n</#if>\n",
        "tags": ["list", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-001",
        },
    },
    {
        "id": "seed-fmt-002",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that greets a user by name. When `userName` is present and non-blank, output a welcome heading with the escaped name. Otherwise output a generic sign-in prompt paragraph.",
        "code": "<#-- Model: userName: string (optional) -->\n<#if userName?? && userName?trim?has_content>\n  <h1>Welcome, ${userName?html}!</h1>\n<#else>\n  <p>Please sign in to continue.</p>\n</#if>\n",
        "tags": ["condition", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-002",
        },
    },
    {
        "id": "seed-fmt-003",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders an ordered list from a sequence `steps` of instruction strings. Prefix each step with its one-based index. Escape all step text.",
        "code": "<#-- Model: steps: sequence of strings -->\n<#if steps?has_content>\n  <ol>\n    <#list steps as step>\n      <li><span class=\"step-number\">${step?index + 1}.</span> ${step?html}</li>\n    </#list>\n  </ol>\n<#else>\n  <p>No steps available.</p>\n</#if>\n",
        "tags": ["list", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-003",
        },
    },
    {
        "id": "seed-fmt-004",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that displays a page title from `pageTitle`. When the title is missing, fall back to the literal text \"Untitled Page\". Escape the title when present.",
        "code": "<#-- Model: pageTitle: string (optional) -->\n<#assign title = pageTitle!\"Untitled Page\">\n<h1>${title?html}</h1>\n",
        "tags": ["condition", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-004",
        },
    },
    {
        "id": "seed-fmt-005",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that formats a numeric `score` using two decimal places via `?string.number`. When `score` is missing, display \"N/A\" instead of a number.",
        "code": "<#-- Model: score: number (optional) -->\n<p class=\"score\">\n  Score:\n  <#if score??>\n    ${score?string.number}\n  <#else>\n    N/A\n  </#if>\n</p>\n",
        "tags": ["formatting", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-005",
        },
    },
    {
        "id": "seed-fmt-006",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders a comma-separated inline list from `tags`, a sequence of strings. Escape each tag. When the sequence is empty, output the word \"none\".",
        "code": "<#-- Model: tags: sequence of strings -->\n<p class=\"tag-list\">\n  <#if tags?has_content>\n    <#list tags as tag>\n      ${tag?html}<#if tag?has_next>, </#if>\n    </#list>\n  <#else>\n    none\n  </#if>\n</p>\n",
        "tags": ["list", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-006",
        },
    },
    {
        "id": "seed-fmt-007",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that shows whether a boolean flag `isActive` is true or false. Render a span with class `active` or `inactive` and human-readable text. Default to inactive when the flag is missing.",
        "code": "<#-- Model: isActive: boolean (optional) -->\n<#assign active = isActive!false>\n<#if active>\n  <span class=\"active\">Active</span>\n<#else>\n  <span class=\"inactive\">Inactive</span>\n</#if>\n",
        "tags": ["condition", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-007",
        },
    },
    {
        "id": "seed-fmt-008",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that lists `authors` as a definition list: each author map has `name` and `role` string fields. Escape both fields. Show a fallback message when no authors exist.",
        "code": "<#-- Model: authors: sequence of maps { name, role } -->\n<#if !authors?has_content>\n  <p>No authors listed.</p>\n<#else>\n  <dl class=\"authors\">\n    <#list authors as author>\n      <dt>${author.name?html}</dt>\n      <dd>${author.role?html}</dd>\n    </#list>\n  </dl>\n</#if>\n",
        "tags": ["list", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-008",
        },
    },
    {
        "id": "seed-fmt-009",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template defining a macro `renderBadge` that accepts `label` and optional `tone` (default \"neutral\"). Output a span with classes `badge` and `badge-{tone}`. Escape the label.",
        "code": "<#-- Macro: renderBadge(label, tone=\"neutral\") -->\n<#macro renderBadge label tone=\"neutral\">\n  <span class=\"badge badge-${tone?html}\">${label?html}</span>\n</#macro>\n\n<#-- Usage example -->\n<@renderBadge label=\"Draft\" tone=\"warning\" />\n",
        "tags": ["macro", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-009",
        },
    },
    {
        "id": "seed-fmt-010",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template with macro `renderProductList` accepting a sequence of product maps (`name`, `price`, `inStock`). Render an unordered list; out-of-stock items show a strikethrough name and \"(unavailable)\" suffix. Escape names and format prices as currency.",
        "code": "<#-- Model: products: sequence of maps { name, price, inStock } -->\n<#macro renderProductList products>\n  <#if !products?has_content>\n    <p>No products available.</p>\n  <#else>\n    <ul class=\"product-list\">\n      <#list products as product>\n        <li>\n          <#if product.inStock!false>\n            <span>${product.name?html}</span>\n            <span>${product.price?string.currency}</span>\n          <#else>\n            <span class=\"unavailable\">\n              <s>${product.name?html}</s> (unavailable)\n            </span>\n            <span>${product.price?string.currency}</span>\n          </#if>\n        </li>\n      </#list>\n    </ul>\n  </#if>\n</#macro>\n",
        "tags": ["macro", "list", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-010",
        },
    },
    {
        "id": "seed-fmt-011",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker page template that includes a shared partial `partials/header.ftl` at the top and `partials/footer.ftl` at the bottom, with main content between them in a `<main>` element.",
        "code": "<#-- Page layout using static includes -->\n<#include \"partials/header.ftl\">\n\n<main id=\"content\">\n  <h1>${pageTitle?html}</h1>\n  <#if bodyHtml??>\n    ${bodyHtml}\n  </#if>\n</main>\n\n<#include \"partials/footer.ftl\">\n",
        "tags": ["include", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-011",
        },
    },
    {
        "id": "seed-fmt-012",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that formats `createdAt` as a medium date and `quantity` as a grouped integer. Both fields may be missing; show \"Unknown date\" and \"0\" respectively as defaults.",
        "code": "<#-- Model: createdAt: date, quantity: number (both optional) -->\n<p>\n  Created:\n  <#if createdAt??>\n    ${createdAt?string.medium}\n  <#else>\n    Unknown date\n  </#if>\n</p>\n<p>\n  Quantity: ${(quantity!0)?string.number}\n</p>\n",
        "tags": ["formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-012",
        },
    },
    {
        "id": "seed-fmt-013",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that displays `totalAmount` formatted as currency inside a receipt summary block. When the amount is missing, show \"$0.00\".",
        "code": "<#-- Model: totalAmount: number (optional) -->\n<div class=\"receipt-summary\">\n  <span class=\"label\">Total</span>\n  <span class=\"amount\">${(totalAmount!0)?string.currency}</span>\n</div>\n",
        "tags": ["formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-013",
        },
    },
    {
        "id": "seed-fmt-014",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that maps an order `status` string to a human-readable label using nested `<#if>` / `<#elseif>` branches for pending, shipped, delivered, and cancelled. Unknown statuses fall back to \"Unknown status\".",
        "code": "<#-- Model: status: string -->\n<#assign normalized = (status!\"\")?lower_case>\n<p class=\"order-status\">\n  Status:\n  <#if normalized == \"pending\">\n    Pending payment\n  <#elseif normalized == \"shipped\">\n    Shipped\n  <#elseif normalized == \"delivered\">\n    Delivered\n  <#elseif normalized == \"cancelled\">\n    Cancelled\n  <#else>\n    Unknown status\n  </#if>\n</p>\n",
        "tags": ["condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-014",
        },
    },
    {
        "id": "seed-fmt-015",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that lists only active users from a `users` sequence. Each user map has `name` and boolean `active`. Skip inactive users inside the list loop. Escape names. Show a message when no active users remain.",
        "code": "<#-- Model: users: sequence of maps { name, active } -->\n<#assign activeUsers = users![]>\n<ul class=\"user-list\">\n  <#assign rendered = 0>\n  <#list activeUsers as user>\n    <#if user.active!false>\n      <#assign rendered = rendered + 1>\n      <li>${user.name?html}</li>\n    </#if>\n  </#list>\n</ul>\n<#if rendered == 0>\n  <p>No active users found.</p>\n</#if>\n",
        "tags": ["list", "condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-015",
        },
    },
    {
        "id": "seed-fmt-016",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders a one-level nested list from `categories`, where each category map has `name` and optional `items` (sequence of strings). Escape all text. Categories without items still render their heading.",
        "code": "<#-- Model: categories: sequence of maps { name, items? } -->\n<ul class=\"category-tree\">\n  <#list categories![] as category>\n    <li>\n      <strong>${category.name?html}</strong>\n      <#if category.items?has_content>\n        <ul>\n          <#list category.items as item>\n            <li>${item?html}</li>\n          </#list>\n        </ul>\n      </#if>\n    </li>\n  </#list>\n</ul>\n",
        "tags": ["nested", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-016",
        },
    },
    {
        "id": "seed-fmt-017",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders `notifications` as a list. When the sequence is empty or missing, show a friendly empty-state paragraph instead of an empty ul element.",
        "code": "<#-- Model: notifications: sequence of strings (optional) -->\n<#if notifications?has_content>\n  <ul class=\"notifications\">\n    <#list notifications as note>\n      <li>${note?html}</li>\n    </#list>\n  </ul>\n<#else>\n  <p class=\"empty-state\">You have no notifications.</p>\n</#if>\n",
        "tags": ["list", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-017",
        },
    },
    {
        "id": "seed-fmt-018",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template defining a macro `alertBox` that wraps nested content in a div with role=\"alert\" and a CSS class derived from `level` (info, warning, error). Use `<#nested>` for the body. Escape the level string used in class names.",
        "code": "<#-- Macro: alertBox(level) with nested body -->\n<#macro alertBox level=\"info\">\n  <div class=\"alert alert-${level?html}\" role=\"alert\">\n    <#nested>\n  </div>\n</#macro>\n\n<#-- Usage example -->\n<@alertBox level=\"warning\">\n  <p>Your session will expire soon.</p>\n</@alertBox>\n",
        "tags": ["custom-directive", "macro", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-018",
        },
    },
    {
        "id": "seed-fmt-019",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderButton` that accepts `label`, optional `href`, and optional `variant` defaulting to \"primary\". Render an anchor when href is provided, otherwise a button element. Escape label and href.",
        "code": "<#-- Macro: renderButton(label, href?, variant=\"primary\") -->\n<#macro renderButton label href=\"\" variant=\"primary\">\n  <#if href?has_content>\n    <a class=\"btn btn-${variant?html}\" href=\"${href?html}\">${label?html}</a>\n  <#else>\n    <button type=\"button\" class=\"btn btn-${variant?html}\">${label?html}</button>\n  </#if>\n</#macro>\n",
        "tags": ["macro", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-019",
        },
    },
    {
        "id": "seed-fmt-020",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that conditionally includes `partials/promo-banner.ftl` only when boolean `showPromo` is true. Always render the main content area regardless of the promo flag.",
        "code": "<#-- Model: showPromo: boolean, pageTitle: string -->\n<#if showPromo!false>\n  <#include \"partials/promo-banner.ftl\">\n</#if>\n\n<main>\n  <h1>${pageTitle?html}</h1>\n</main>\n",
        "tags": ["include", "condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-020",
        },
    },
    {
        "id": "seed-fmt-021",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `statusBadge` that maps a `status` string to badge text and CSS modifier classes for open, in_progress, and closed. Unknown statuses use a neutral badge. Escape status-derived text.",
        "code": "<#-- Macro: statusBadge(status) -->\n<#macro statusBadge status>\n  <#assign key = (status!\"\")?lower_case?replace(\" \", \"_\")>\n  <#if key == \"open\">\n    <span class=\"badge badge-open\">Open</span>\n  <#elseif key == \"in_progress\">\n    <span class=\"badge badge-progress\">In progress</span>\n  <#elseif key == \"closed\">\n    <span class=\"badge badge-closed\">Closed</span>\n  <#else>\n    <span class=\"badge badge-neutral\">${(status!\"Unknown\")?html}</span>\n  </#if>\n</#macro>\n",
        "tags": ["macro", "condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-021",
        },
    },
    {
        "id": "seed-fmt-022",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders a price list table from `lineItems`, each map having `description` and `amount`. Escape descriptions and format amounts as currency. Show a table footnote row with `grandTotal`.",
        "code": "<#-- Model: lineItems: sequence of { description, amount }, grandTotal: number -->\n<table class=\"price-list\">\n  <thead>\n    <tr><th>Item</th><th>Amount</th></tr>\n  </thead>\n  <tbody>\n    <#list lineItems![] as item>\n      <tr>\n        <td>${item.description?html}</td>\n        <td>${item.amount?string.currency}</td>\n      </tr>\n    </#list>\n  </tbody>\n  <tfoot>\n    <tr>\n      <th>Total</th>\n      <td>${(grandTotal!0)?string.currency}</td>\n    </tr>\n  </tfoot>\n</table>\n",
        "tags": ["list", "formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-022",
        },
    },
    {
        "id": "seed-fmt-023",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that assigns a priority label (Low, Medium, High, Critical) from numeric `priorityLevel` using nested conditionals. Values outside 1–4 map to \"Unspecified\".",
        "code": "<#-- Model: priorityLevel: number (optional) -->\n<#assign level = priorityLevel!0>\n<span class=\"priority\">\n  <#if level == 1>Low\n  <#elseif level == 2>Medium\n  <#elseif level == 3>High\n  <#elseif level == 4>Critical\n  <#else>Unspecified\n  </#if>\n</span>\n",
        "tags": ["condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-023",
        },
    },
    {
        "id": "seed-fmt-024",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders FAQ sections from `sections`, each with `title` and `questions` (sequence of maps with `q` and `a`). Escape all text. Nest questions inside each section heading.",
        "code": "<#-- Model: sections: sequence of { title, questions: [{ q, a }] } -->\n<div class=\"faq\">\n  <#list sections![] as section>\n    <section>\n      <h2>${section.title?html}</h2>\n      <dl>\n        <#list section.questions![] as qa>\n          <dt>${qa.q?html}</dt>\n          <dd>${qa.a?html}</dd>\n        </#list>\n      </dl>\n    </section>\n  </#list>\n</div>\n",
        "tags": ["nested", "list", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-024",
        },
    },
    {
        "id": "seed-fmt-025",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that displays `completionRate` as a percentage with one decimal place using `?string.percent`. When missing, show \"0%\".",
        "code": "<#-- Model: completionRate: number between 0 and 1 (optional) -->\n<p class=\"completion\">\n  Completion: ${(completionRate!0)?string.percent}\n</p>\n",
        "tags": ["formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-025",
        },
    },
    {
        "id": "seed-fmt-026",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `initialsAvatar` that derives two-letter initials from a `fullName` string and renders them inside a span with class `avatar`. Escape the initials output.",
        "code": "<#-- Macro: initialsAvatar(fullName) -->\n<#macro initialsAvatar fullName>\n  <#assign parts = (fullName!\"\")?trim?split(\"\\\\s+\", \"r\")>\n  <#assign initials = \"\">\n  <#list parts as part>\n    <#if part?has_content && initials?length < 2>\n      <#assign initials = initials + part?substring(0, 1)?upper_case>\n    </#if>\n  </#list>\n  <span class=\"avatar\" aria-hidden=\"true\">${initials?html}</span>\n</#macro>\n",
        "tags": ["macro", "formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-026",
        },
    },
    {
        "id": "seed-fmt-027",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that builds a two-column feature grid by iterating `features` and wrapping every odd-indexed item in a new row div. Each feature map has `title` and `summary`. Escape both fields.",
        "code": "<#-- Model: features: sequence of maps { title, summary } -->\n<div class=\"feature-grid\">\n  <#list features![] as feature>\n    <#if feature?index % 2 == 0>\n      <div class=\"row\">\n    </#if>\n    <article>\n      <h3>${feature.title?html}</h3>\n      <p>${feature.summary?html}</p>\n    </article>\n    <#if feature?index % 2 == 1 || !feature?has_next>\n      </div>\n    </#if>\n  </#list>\n</div>\n",
        "tags": ["list", "nested", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-027",
        },
    },
    {
        "id": "seed-fmt-028",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that displays `publishedOn` formatted as a long date when present, otherwise the literal \"Not published\". Use appropriate date formatting built-ins.",
        "code": "<#-- Model: publishedOn: date (optional) -->\n<p class=\"published-on\">\n  <#if publishedOn??>\n    Published on ${publishedOn?string.long}\n  <#else>\n    Not published\n  </#if>\n</p>\n",
        "tags": ["condition", "formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-028",
        },
    },
    {
        "id": "seed-fmt-029",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `truncateText` that outputs at most `maxLength` characters of `text`, appending an ellipsis when truncated. Default maxLength to 80. Escape the result.",
        "code": "<#-- Macro: truncateText(text, maxLength=80) -->\n<#macro truncateText text maxLength=80>\n  <#assign value = text!\"\">\n  <#if value?length <= maxLength>\n    ${value?html}\n  <#else>\n    ${value?substring(0, maxLength)?html}&hellip;\n  </#if>\n</#macro>\n",
        "tags": ["macro", "formatting", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-029",
        },
    },
    {
        "id": "seed-fmt-030",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderTableRows` that accepts a sequence of row maps with `cells` (sequence of strings) and outputs tr/td elements. Escape every cell value.",
        "code": "<#-- Macro: renderTableRows(rows) -->\n<#macro renderTableRows rows>\n  <#list rows![] as row>\n    <tr>\n      <#list row.cells![] as cell>\n        <td>${cell?html}</td>\n      </#list>\n    </tr>\n  </#list>\n</#macro>\n",
        "tags": ["macro", "list", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-030",
        },
    },
    {
        "id": "seed-fmt-031",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders a sidebar navigation list from `navItems` (maps with `label` and `url`). Mark the item whose `url` equals `currentPath` with class `active`. Escape labels and URLs.",
        "code": "<#-- Model: navItems: [{ label, url }], currentPath: string -->\n<nav aria-label=\"Sidebar\">\n  <ul>\n    <#list navItems![] as item>\n      <#assign isActive = (item.url!\"\") == (currentPath!\"\")>\n      <li<#if isActive> class=\"active\"</#if>>\n        <a href=\"${item.url?html}\">${item.label?html}</a>\n      </li>\n    </#list>\n  </ul>\n</nav>\n",
        "tags": ["list", "condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-031",
        },
    },
    {
        "id": "seed-fmt-032",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that groups `tasks` by string `status` without a hash built-in helper: iterate tasks and emit a heading each time the status changes, listing task titles beneath. Escape titles and status labels.",
        "code": "<#-- Model: tasks: sequence of maps { title, status } sorted by status -->\n<#assign previousStatus = \"\">\n<#list tasks![] as task>\n  <#if task.status!\"\" != previousStatus>\n    <#if previousStatus?has_content></ul></#if>\n    <h3>${task.status?html}</h3>\n    <ul>\n    <#assign previousStatus = task.status!\"\">\n  </#if>\n  <li>${task.title?html}</li>\n  <#if !task?has_next></ul></#if>\n</#list>\n",
        "tags": ["list", "nested", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-032",
        },
    },
    {
        "id": "seed-fmt-033",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `fieldLabel` that renders a label element for `fieldId` and `caption`, optionally showing a required asterisk when `required` is true. Escape fieldId and caption in attributes and text.",
        "code": "<#-- Macro: fieldLabel(fieldId, caption, required=false) -->\n<#macro fieldLabel fieldId caption required=false>\n  <label for=\"${fieldId?html}\">\n    ${caption?html}<#if required> <span aria-hidden=\"true\">*</span></#if>\n  </label>\n</#macro>\n",
        "tags": ["macro", "condition", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-033",
        },
    },
    {
        "id": "seed-fmt-034",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker recursive macro `renderCommentTree` that renders nested comments from maps with `author`, `body`, and optional `replies` sequence. Indent nested replies in a nested ul. Escape author and body text.",
        "code": "<#-- Model: comments: sequence of maps { author, body, replies? } -->\n<#macro renderCommentTree comments>\n  <ul class=\"comment-tree\">\n    <#list comments![] as comment>\n      <li>\n        <p><strong>${comment.author?html}</strong>: ${comment.body?html}</p>\n        <#if comment.replies?has_content>\n          <@renderCommentTree comments=comment.replies />\n        </#if>\n      </li>\n    </#list>\n  </ul>\n</#macro>\n",
        "tags": ["macro", "nested", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-034",
        },
    },
    {
        "id": "seed-fmt-035",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderMeta` with parameters `title`, optional `description` defaulting to empty, and optional `robots` defaulting to \"index,follow\". Output title and meta description tags with escaped values.",
        "code": "<#-- Macro: renderMeta(title, description=\"\", robots=\"index,follow\") -->\n<#macro renderMeta title description=\"\" robots=\"index,follow\">\n  <title>${title?html}</title>\n  <#if description?has_content>\n    <meta name=\"description\" content=\"${description?html}\">\n  </#if>\n  <meta name=\"robots\" content=\"${robots?html}\">\n</#macro>\n",
        "tags": ["macro", "formatting", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-035",
        },
    },
    {
        "id": "seed-fmt-036",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker layout macro `pageLayout` accepting `title` and nested content. The macro renders html/head/body scaffolding, includes `partials/head-meta.ftl`, and places nested content inside main. Escape the title.",
        "code": "<#-- Macro: pageLayout(title) with nested main content -->\n<#macro pageLayout title>\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <#include \"partials/head-meta.ftl\">\n  <title>${title?html}</title>\n</head>\n<body>\n  <main>\n    <#nested>\n  </main>\n</body>\n</html>\n</#macro>\n",
        "tags": ["include", "macro", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-036",
        },
    },
    {
        "id": "seed-fmt-037",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that displays profile fields `bio`, `website`, and `location`, using \"Not provided\" for each missing or blank string. Escape all user-provided values when present.",
        "code": "<#-- Model: bio, website, location: strings (optional) -->\n<dl class=\"profile\">\n  <dt>Bio</dt>\n  <dd><#if bio?has_content>${bio?html}<#else>Not provided</#if></dd>\n  <dt>Website</dt>\n  <dd><#if website?has_content>${website?html}<#else>Not provided</#if></dd>\n  <dt>Location</dt>\n  <dd><#if location?has_content>${location?html}<#else>Not provided</#if></dd>\n</dl>\n",
        "tags": ["condition", "formatting", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-037",
        },
    },
    {
        "id": "seed-fmt-038",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that paginates `allItems` using numeric `page` and `pageSize`, rendering only the current slice via list slicing. Show current page, page count, and formatted item count. Escape item names.",
        "code": "<#-- Model: allItems: sequence of { name }, page: number, pageSize: number -->\n<#assign currentPage = (page!1)?number>\n<#assign size = (pageSize!10)?number>\n<#assign total = allItems?size>\n<#assign pageCount = ((total + size - 1) / size)?int>\n<#assign offset = (currentPage - 1) * size>\n\n<ul>\n  <#list allItems[offset..*size] as item>\n    <li>${item.name?html}</li>\n  <#else>\n    <li>No items on this page.</li>\n  </#list>\n</ul>\n<p>Page ${currentPage} of ${pageCount?c} (${total?c} items)</p>\n",
        "tags": ["list", "formatting", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-038",
        },
    },
    {
        "id": "seed-fmt-039",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderDataTable` that accepts `columns` (sequence of header strings) and `rows` (sequence of cell sequences), outputting a complete table with thead and tbody. Escape all header and cell values.",
        "code": "<#-- Macro: renderDataTable(columns, rows) -->\n<#macro renderDataTable columns rows>\n  <table>\n    <thead>\n      <tr>\n        <#list columns![] as column>\n          <th scope=\"col\">${column?html}</th>\n        </#list>\n      </tr>\n    </thead>\n    <tbody>\n      <#list rows![] as row>\n        <tr>\n          <#list row as cell>\n            <td>${cell?html}</td>\n          </#list>\n        </tr>\n      </#list>\n    </tbody>\n  </table>\n</#macro>\n",
        "tags": ["macro", "list", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-039",
        },
    },
    {
        "id": "seed-fmt-040",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderMenu` that renders a two-level navigation menu from `menuItems` with optional nested `children` sequences. Top-level items without children render as plain links. Escape labels and URLs.",
        "code": "<#-- Model: menuItems: [{ label, url, children? }] -->\n<#macro renderMenu items>\n  <ul class=\"menu\">\n    <#list items![] as item>\n      <li>\n        <a href=\"${item.url?html}\">${item.label?html}</a>\n        <#if item.children?has_content>\n          <ul>\n            <#list item.children as child>\n              <li><a href=\"${child.url?html}\">${child.label?html}</a></li>\n            </#list>\n          </ul>\n        </#if>\n      </li>\n    </#list>\n  </ul>\n</#macro>\n",
        "tags": ["macro", "nested", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-040",
        },
    },
    {
        "id": "seed-fmt-041",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that composes a sidebar from static includes: `partials/nav-profile.ftl`, a dynamic list of `shortcuts`, then `partials/nav-footer.ftl`. Escape shortcut labels and hrefs in the list loop.",
        "code": "<#-- Model: shortcuts: sequence of { label, href } -->\n<aside class=\"sidebar\">\n  <#include \"partials/nav-profile.ftl\">\n  <ul class=\"shortcuts\">\n    <#list shortcuts![] as link>\n      <li><a href=\"${link.href?html}\">${link.label?html}</a></li>\n    </#list>\n  </ul>\n  <#include \"partials/nav-footer.ftl\">\n</aside>\n",
        "tags": ["include", "list", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-041",
        },
    },
    {
        "id": "seed-fmt-042",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders `events` grouped by `date` string, emitting a heading per date and a nested list of event titles and times. Assume events are pre-sorted by date. Escape all displayed text.",
        "code": "<#-- Model: events: [{ date, title, time }] sorted by date -->\n<#assign lastDate = \"\">\n<div class=\"event-groups\">\n  <#list events![] as event>\n    <#if event.date!\"\" != lastDate>\n      <#if lastDate?has_content></ul></section></#if>\n      <section>\n        <h2>${event.date?html}</h2>\n        <ul>\n      <#assign lastDate = event.date!\"\">\n    </#if>\n    <li><time>${event.time?html}</time> ${event.title?html}</li>\n    <#if !event?has_next></ul></section></#if>\n  </#list>\n</div>\n",
        "tags": ["nested", "list", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-042",
        },
    },
    {
        "id": "seed-fmt-043",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `banner` that selects icon and CSS class from `kind` (success, error, info) and renders a paragraph with nested body content via `<#nested>`. Unknown kinds default to info styling.",
        "code": "<#-- Macro: banner(kind) with nested message body -->\n<#macro banner kind=\"info\">\n  <#assign cssKind = kind?lower_case>\n  <#if cssKind != \"success\" && cssKind != \"error\" && cssKind != \"info\">\n    <#assign cssKind = \"info\">\n  </#if>\n  <div class=\"banner banner-${cssKind?html}\" role=\"status\">\n    <#nested>\n  </div>\n</#macro>\n",
        "tags": ["macro", "condition", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-043",
        },
    },
    {
        "id": "seed-fmt-044",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `card` with parameters `title` and optional `footer`. Render a div.card containing a header, nested body content, and footer block only when the footer parameter is non-empty. Escape title and footer.",
        "code": "<#-- Macro: card(title, footer=\"\") with nested body -->\n<#macro card title footer=\"\">\n  <article class=\"card\">\n    <header><h3>${title?html}</h3></header>\n    <div class=\"card-body\">\n      <#nested>\n    </div>\n    <#if footer?has_content>\n      <footer>${footer?html}</footer>\n    </#if>\n  </article>\n</#macro>\n",
        "tags": ["macro", "custom-directive", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-044",
        },
    },
    {
        "id": "seed-fmt-045",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that renders a changelog from `releases`, each with `version`, `date`, and nested `changes` list. Format dates as medium strings. Escape version labels and change descriptions.",
        "code": "<#-- Model: releases: [{ version, date, changes: [string] }] -->\n<div class=\"changelog\">\n  <#list releases![] as release>\n    <section>\n      <h2>${release.version?html} <small>${release.date?string.medium}</small></h2>\n      <ul>\n        <#list release.changes![] as change>\n          <li>${change?html}</li>\n        </#list>\n      </ul>\n    </section>\n  </#list>\n</div>\n",
        "tags": ["list", "nested", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-045",
        },
    },
    {
        "id": "seed-fmt-046",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `requireFields` that accepts a map `model` and a sequence of required key names. When any key is missing or blank, render an error div listing the missing keys. Otherwise invoke nested content. Escape key names in output.",
        "code": "<#-- Macro: requireFields(model, requiredKeys) with nested body -->\n<#macro requireFields model requiredKeys>\n  <#assign missing = []>\n  <#list requiredKeys as key>\n    <#assign value = model[key]!\"\">\n    <#if !value?has_content>\n      <#assign missing = missing + [key]>\n    </#if>\n  </#list>\n  <#if missing?has_content>\n    <div class=\"model-error\" role=\"alert\">\n      Missing required fields:\n      <ul>\n        <#list missing as key>\n          <li>${key?html}</li>\n        </#list>\n      </ul>\n    </div>\n  <#else>\n    <#nested>\n  </#if>\n</#macro>\n",
        "tags": ["macro", "condition", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-046",
        },
    },
    {
        "id": "seed-fmt-047",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that builds a category trail from a flat `categories` list (maps with `id`, `name`, `parentId`). Walk parent links from `currentCategoryId` upward, then render names in root-to-leaf order separated by \" / \". Escape names.",
        "code": "<#-- Model: categories: [{ id, name, parentId }], currentCategoryId: string -->\n<#assign trail = []>\n<#assign cursor = currentCategoryId!\"\">\n<#list 1..20 as _>\n  <#if !cursor?has_content><#break></#if>\n  <#assign match = \"\">\n  <#list categories![] as cat>\n    <#if cat.id == cursor>\n      <#assign trail = [cat] + trail>\n      <#assign cursor = cat.parentId!\"\">\n      <#assign match = cat.id>\n      <#break>\n    </#if>\n  </#list>\n  <#if !match?has_content><#break></#if>\n</#list>\n<nav aria-label=\"Category trail\">\n  <#list trail as crumb>\n    ${crumb.name?html}<#if crumb?has_next> / </#if>\n  </#list>\n</nav>\n",
        "tags": ["nested", "condition", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-047",
        },
    },
    {
        "id": "seed-fmt-048",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker macro `renderSpecTable` that renders rows from `specs` (maps with `label`, `value`, and optional boolean `highlight`). Highlighted rows wrap the value in strong. Escape labels and values.",
        "code": "<#-- Macro: renderSpecTable(specs) -->\n<#macro renderSpecTable specs>\n  <table class=\"spec-table\">\n    <tbody>\n      <#list specs![] as spec>\n        <tr<#if spec.highlight!false> class=\"highlight\"</#if>>\n          <th scope=\"row\">${spec.label?html}</th>\n          <td>\n            <#if spec.highlight!false>\n              <strong>${spec.value?html}</strong>\n            <#else>\n              ${spec.value?html}\n            </#if>\n          </td>\n        </tr>\n      </#list>\n    </tbody>\n  </table>\n</#macro>\n",
        "tags": ["macro", "list", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-048",
        },
    },
    {
        "id": "seed-fmt-049",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker recursive macro `renderSiteMap` that walks a tree of `nodes` (maps with `url`, `label`, optional `children`), stopping recursion at `maxDepth`. Render nested ul elements. Escape labels and URLs.",
        "code": "<#-- Macro: renderSiteMap(nodes, depth=0, maxDepth=3) -->\n<#macro renderSiteMap nodes depth=0 maxDepth=3>\n  <#if depth >= maxDepth>\n    <#return>\n  </#if>\n  <ul class=\"sitemap depth-${depth?c}\">\n    <#list nodes![] as node>\n      <li>\n        <a href=\"${node.url?html}\">${node.label?html}</a>\n        <#if node.children?has_content>\n          <@renderSiteMap nodes=node.children depth=depth + 1 maxDepth=maxDepth />\n        </#if>\n      </li>\n    </#list>\n  </ul>\n</#macro>\n",
        "tags": ["macro", "nested", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-049",
        },
    },
    {
        "id": "seed-fmt-050",
        "targetLanguage": "FreeMarker",
        "instruction": "Write a FreeMarker template that filters `articles` to those matching optional `query` substring in the title (case-insensitive), sorts nothing (preserve input order), paginates with `page`/`pageSize`, and shows an empty-state when the filtered slice is blank. Escape titles.",
        "code": "<#-- Model: articles: [{ title }], query: string, page, pageSize -->\n<#assign term = (query!\"\")?lower_case>\n<#assign filtered = []>\n<#list articles![] as article>\n  <#assign title = article.title!\"\">\n  <#if !term?has_content || title?lower_case?contains(term)>\n    <#assign filtered = filtered + [article]>\n  </#if>\n</#list>\n<#assign pageNum = (page!1)?number>\n<#assign size = (pageSize!5)?number>\n<#assign offset = (pageNum - 1) * size>\n<ul>\n  <#list filtered[offset..*size] as article>\n    <li>${article.title?html}</li>\n  <#else>\n    <li>No articles matched your search.</li>\n  </#list>\n</ul>\n",
        "tags": ["list", "condition", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: FMT-050",
        },
    },
]
