"""Gold seed catalog — HTML (Stage 2). 50 manually-authored GoldSeedExample dicts."""

HTML_SEEDS: list[dict] = [
    {
        "id": "seed-html-001",
        "targetLanguage": "HTML",
        "instruction": "Write a minimal HTML5 page with a semantic article containing a header with an h1 and a footer with a copyright paragraph. Use lang=\"en\" on the root element.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Article</title>\n  </head>\n  <body>\n    <article>\n      <header>\n        <h1>Quarterly update</h1>\n      </header>\n      <p>Revenue increased across all regions during Q2.</p>\n      <footer>\n        <p>Copyright 2026 Example Corp.</p>\n      </footer>\n    </article>\n  </body>\n</html>",
        "tags": ["semantic", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-001",
        },
    },
    {
        "id": "seed-html-002",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 navigation landmark using a nav element with an unordered list of three internal links to Home, Products, and Contact sections.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Site navigation</title>\n  </head>\n  <body>\n    <nav aria-label=\"Primary\">\n      <ul>\n        <li><a href=\"#home\">Home</a></li>\n        <li><a href=\"#products\">Products</a></li>\n        <li><a href=\"#contact\">Contact</a></li>\n      </ul>\n    </nav>\n  </body>\n</html>",
        "tags": ["semantic", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-002",
        },
    },
    {
        "id": "seed-html-003",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 section with a single h2 heading and two paragraphs of body text. Do not use div wrappers for the section content.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Section example</title>\n  </head>\n  <body>\n    <section>\n      <h2>Shipping policy</h2>\n      <p>Orders placed before noon ship the same business day.</p>\n      <p>International delivery may require additional customs processing.</p>\n    </section>\n  </body>\n</html>",
        "tags": ["semantic", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-003",
        },
    },
    {
        "id": "seed-html-004",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a main landmark containing one h1 and a short paragraph. The main element must be the sole top-level content wrapper.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Main landmark</title>\n  </head>\n  <body>\n    <main>\n      <h1>Account overview</h1>\n      <p>Your subscription renews on the first of each month.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["layout", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-004",
        },
    },
    {
        "id": "seed-html-005",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 ordered list of three steps for resetting a password. Each list item must be a complete sentence.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Password reset steps</title>\n  </head>\n  <body>\n    <ol>\n      <li>Open the sign-in page and choose Forgot password.</li>\n      <li>Enter the email address linked to your account.</li>\n      <li>Follow the link in the email to set a new password.</li>\n    </ol>\n  </body>\n</html>",
        "tags": ["semantic", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-005",
        },
    },
    {
        "id": "seed-html-006",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 blockquote citing a customer review. Include a cite element referencing the reviewer name.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Customer quote</title>\n  </head>\n  <body>\n    <blockquote cite=\"https://example.com/reviews/42\">\n      <p>The onboarding checklist saved our team hours every week.</p>\n      <footer>— <cite>Jordan Lee</cite>, Operations lead</footer>\n    </blockquote>\n  </body>\n</html>",
        "tags": ["semantic", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-006",
        },
    },
    {
        "id": "seed-html-007",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 head section with charset utf-8, a viewport meta tag, and a descriptive title. The body may be empty.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <title>Inventory overview</title>\n  </head>\n  <body></body>\n</html>",
        "tags": ["metadata", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-007",
        },
    },
    {
        "id": "seed-html-008",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a header, nav, main, and footer in document order. Each landmark contains only a single heading identifying its role.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Landmark skeleton</title>\n  </head>\n  <body>\n    <header><h1>Site header</h1></header>\n    <nav aria-label=\"Primary\"><h2>Navigation</h2></nav>\n    <main><h2>Main content</h2></main>\n    <footer><h2>Footer</h2></footer>\n  </body>\n</html>",
        "tags": ["layout", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-008",
        },
    },
    {
        "id": "seed-html-009",
        "targetLanguage": "HTML",
        "instruction": "Write a semantic HTML5 contact form with required fields for name, email (type email), and message (textarea). Link each label to its control with for and id attributes.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Contact form</title>\n  </head>\n  <body>\n    <main>\n      <h1>Contact us</h1>\n      <form action=\"/contact\" method=\"post\">\n        <p>\n          <label for=\"contact-name\">Name</label>\n          <input id=\"contact-name\" name=\"name\" type=\"text\" required autocomplete=\"name\" />\n        </p>\n        <p>\n          <label for=\"contact-email\">Email</label>\n          <input id=\"contact-email\" name=\"email\" type=\"email\" required autocomplete=\"email\" />\n        </p>\n        <p>\n          <label for=\"contact-message\">Message</label>\n          <textarea id=\"contact-message\" name=\"message\" rows=\"5\" required></textarea>\n        </p>\n        <p><button type=\"submit\">Send message</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "accessibility", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-009",
        },
    },
    {
        "id": "seed-html-010",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form with a fieldset and legend grouping three radio buttons for delivery speed: Standard, Express, and Overnight. Only one option may be selected.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Delivery options</title>\n  </head>\n  <body>\n    <form action=\"/checkout/shipping\" method=\"post\">\n      <fieldset>\n        <legend>Delivery speed</legend>\n        <p>\n          <label>\n            <input type=\"radio\" name=\"speed\" value=\"standard\" checked />\n            Standard\n          </label>\n        </p>\n        <p>\n          <label>\n            <input type=\"radio\" name=\"speed\" value=\"express\" />\n            Express\n          </label>\n        </p>\n        <p>\n          <label>\n            <input type=\"radio\" name=\"speed\" value=\"overnight\" />\n            Overnight\n          </label>\n        </p>\n      </fieldset>\n      <p><button type=\"submit\">Continue</button></p>\n    </form>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-010",
        },
    },
    {
        "id": "seed-html-011",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 select element with two optgroups labeled Fruits and Vegetables. Each group must contain at least two option elements.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Produce selector</title>\n  </head>\n  <body>\n    <form action=\"/order\" method=\"post\">\n      <label for=\"produce\">Choose an item</label>\n      <select id=\"produce\" name=\"produce\" required>\n        <optgroup label=\"Fruits\">\n          <option value=\"apple\">Apple</option>\n          <option value=\"banana\">Banana</option>\n        </optgroup>\n        <optgroup label=\"Vegetables\">\n          <option value=\"carrot\">Carrot</option>\n          <option value=\"spinach\">Spinach</option>\n        </optgroup>\n      </select>\n      <p><button type=\"submit\">Add to cart</button></p>\n    </form>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-011",
        },
    },
    {
        "id": "seed-html-012",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a skip link targeting the main landmark. The skip link must be the first focusable element in the body.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Skip link page</title>\n  </head>\n  <body>\n    <a href=\"#main-content\">Skip to main content</a>\n    <header>\n      <h1>Support center</h1>\n      <nav aria-label=\"Primary\">\n        <ul>\n          <li><a href=\"/help\">Help</a></li>\n          <li><a href=\"/status\">Status</a></li>\n        </ul>\n      </nav>\n    </header>\n    <main id=\"main-content\">\n      <h2>Ticket history</h2>\n      <p>No open tickets.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["accessibility", "layout", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-012",
        },
    },
    {
        "id": "seed-html-013",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 status message region using role=\"status\" and aria-live=\"polite\" for non-critical save confirmations.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Save status</title>\n  </head>\n  <body>\n    <main>\n      <h1>Profile settings</h1>\n      <form action=\"/profile\" method=\"post\">\n        <label for=\"display-name\">Display name</label>\n        <input id=\"display-name\" name=\"displayName\" type=\"text\" />\n        <p><button type=\"submit\">Save changes</button></p>\n      </form>\n      <p role=\"status\" aria-live=\"polite\">Your changes were saved successfully.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["accessibility", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-013",
        },
    },
    {
        "id": "seed-html-014",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 data table with a caption, thead, and tbody. Use scope=\"col\" on column header cells for Region, Revenue, and Growth.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Regional revenue</title>\n  </head>\n  <body>\n    <table>\n      <caption>Q2 revenue by region</caption>\n      <thead>\n        <tr>\n          <th scope=\"col\">Region</th>\n          <th scope=\"col\">Revenue</th>\n          <th scope=\"col\">Growth</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <th scope=\"row\">North America</th>\n          <td>$1.2M</td>\n          <td>8%</td>\n        </tr>\n        <tr>\n          <th scope=\"row\">Europe</th>\n          <td>$980K</td>\n          <td>5%</td>\n        </tr>\n      </tbody>\n    </table>\n  </body>\n</html>",
        "tags": ["tables", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-014",
        },
    },
    {
        "id": "seed-html-015",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 table separating header and body rows with thead and tbody. Include three columns: SKU, Name, and Quantity.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Inventory table</title>\n  </head>\n  <body>\n    <table>\n      <thead>\n        <tr>\n          <th>SKU</th>\n          <th>Name</th>\n          <th>Quantity</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <td>SKU-1001</td>\n          <td>Widget A</td>\n          <td>24</td>\n        </tr>\n        <tr>\n          <td>SKU-1002</td>\n          <td>Widget B</td>\n          <td>12</td>\n        </tr>\n      </tbody>\n    </table>\n  </body>\n</html>",
        "tags": ["tables", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-015",
        },
    },
    {
        "id": "seed-html-016",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 head with charset, viewport, and a meta description summarizing the page purpose for search engines.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta\n      name=\"description\"\n      content=\"Manage team permissions, audit logs, and billing settings for your organization.\"\n    />\n    <title>Organization settings</title>\n  </head>\n  <body>\n    <main>\n      <h1>Organization settings</h1>\n    </main>\n  </body>\n</html>",
        "tags": ["metadata", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-016",
        },
    },
    {
        "id": "seed-html-017",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 head with author, robots, and theme-color meta tags for a public documentation page.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"author\" content=\"Example Corp Documentation Team\" />\n    <meta name=\"robots\" content=\"index, follow\" />\n    <meta name=\"theme-color\" content=\"#1a3a5c\" />\n    <title>API reference — Authentication</title>\n  </head>\n  <body>\n    <main>\n      <h1>Authentication</h1>\n    </main>\n  </body>\n</html>",
        "tags": ["metadata", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-017",
        },
    },
    {
        "id": "seed-html-018",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 figure containing an img with descriptive alt text and a figcaption explaining the chart shown.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Monthly chart</title>\n  </head>\n  <body>\n    <figure>\n      <img\n        src=\"/assets/charts/signups-may.png\"\n        alt=\"Bar chart showing signups rising from 120 in week one to 210 in week four\"\n        width=\"640\"\n        height=\"360\"\n      />\n      <figcaption>May signup trend across four weekly intervals.</figcaption>\n    </figure>\n  </body>\n</html>",
        "tags": ["media", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-018",
        },
    },
    {
        "id": "seed-html-019",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 audio element with controls and fallback paragraph text for browsers that cannot play audio.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Podcast clip</title>\n  </head>\n  <body>\n    <main>\n      <h1>Episode preview</h1>\n      <audio controls>\n        <source src=\"/media/ep12-preview.mp3\" type=\"audio/mpeg\" />\n        <p>Your browser does not support embedded audio. Download the preview instead.</p>\n      </audio>\n    </main>\n  </body>\n</html>",
        "tags": ["media", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-019",
        },
    },
    {
        "id": "seed-html-020",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a main landmark and a complementary aside landmark. The aside summarizes related links without using CSS layout properties.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Article with aside</title>\n  </head>\n  <body>\n    <main>\n      <article>\n        <h1>Release notes 4.2</h1>\n        <p>Version 4.2 adds bulk export and improved audit logging.</p>\n      </article>\n    </main>\n    <aside aria-label=\"Related resources\">\n      <h2>Related</h2>\n      <ul>\n        <li><a href=\"/docs/migration\">Migration guide</a></li>\n        <li><a href=\"/docs/changelog\">Full changelog</a></li>\n      </ul>\n    </aside>\n  </body>\n</html>",
        "tags": ["layout", "semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-020",
        },
    },
    {
        "id": "seed-html-021",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 address element inside a footer with a physical mailing address and a contact email link.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Company footer</title>\n  </head>\n  <body>\n    <footer>\n      <address>\n        Example Corp<br />\n        100 Market Street<br />\n        San Francisco, CA 94105<br />\n        <a href=\"mailto:support@example.com\">support@example.com</a>\n      </address>\n    </footer>\n  </body>\n</html>",
        "tags": ["semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-021",
        },
    },
    {
        "id": "seed-html-022",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 time element with a machine-readable datetime attribute for a published article timestamp.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Published article</title>\n  </head>\n  <body>\n    <article>\n      <header>\n        <h1>Security patch advisory</h1>\n        <p>Published <time datetime=\"2026-06-20T09:30:00Z\">June 20, 2026</time></p>\n      </header>\n      <p>A maintenance window is scheduled for critical infrastructure updates.</p>\n    </article>\n  </body>\n</html>",
        "tags": ["semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-022",
        },
    },
    {
        "id": "seed-html-023",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form with a checkbox group inside a fieldset. Users may select multiple notification channels: Email, SMS, and Push.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Notification preferences</title>\n  </head>\n  <body>\n    <form action=\"/settings/notifications\" method=\"post\">\n      <fieldset>\n        <legend>Notification channels</legend>\n        <p>\n          <label>\n            <input type=\"checkbox\" name=\"channels\" value=\"email\" checked />\n            Email\n          </label>\n        </p>\n        <p>\n          <label>\n            <input type=\"checkbox\" name=\"channels\" value=\"sms\" />\n            SMS\n          </label>\n        </p>\n        <p>\n          <label>\n            <input type=\"checkbox\" name=\"channels\" value=\"push\" />\n            Push\n          </label>\n        </p>\n      </fieldset>\n      <p><button type=\"submit\">Save preferences</button></p>\n    </form>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-023",
        },
    },
    {
        "id": "seed-html-024",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 search form using input type=\"search\" and a submit button labeled Search. Place the form inside a search landmark.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Site search</title>\n  </head>\n  <body>\n    <header>\n      <search>\n        <form action=\"/search\" method=\"get\" role=\"search\">\n          <label for=\"site-query\">Search documentation</label>\n          <input id=\"site-query\" name=\"q\" type=\"search\" required />\n          <button type=\"submit\">Search</button>\n        </form>\n      </search>\n    </header>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-024",
        },
    },
    {
        "id": "seed-html-025",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 section labeled with aria-labelledby pointing to its h2 heading. The section contains one explanatory paragraph.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Labeled section</title>\n  </head>\n  <body>\n    <section aria-labelledby=\"billing-heading\">\n      <h2 id=\"billing-heading\">Billing cycle</h2>\n      <p>Invoices are generated on the first day of each month.</p>\n    </section>\n  </body>\n</html>",
        "tags": ["accessibility", "semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-025",
        },
    },
    {
        "id": "seed-html-026",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 details element with a summary titled Show API limits and hidden content listing three rate-limit tiers.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>API limits</title>\n  </head>\n  <body>\n    <details>\n      <summary>Show API limits</summary>\n      <ul>\n        <li>Free: 100 requests per hour</li>\n        <li>Pro: 1,000 requests per hour</li>\n        <li>Enterprise: 10,000 requests per hour</li>\n      </ul>\n    </details>\n  </body>\n</html>",
        "tags": ["semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-026",
        },
    },
    {
        "id": "seed-html-027",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 video element with controls, a poster image, and fallback text for unsupported browsers.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Product demo</title>\n  </head>\n  <body>\n    <main>\n      <h1>Product walkthrough</h1>\n      <video controls poster=\"/media/demo-poster.jpg\" width=\"640\" height=\"360\">\n        <source src=\"/media/demo.mp4\" type=\"video/mp4\" />\n        <p>Your browser does not support embedded video.</p>\n      </video>\n    </main>\n  </body>\n</html>",
        "tags": ["media", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-027",
        },
    },
    {
        "id": "seed-html-028",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 password input with autocomplete=\"current-password\" inside a sign-in form. Include a labeled email field.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Sign in</title>\n  </head>\n  <body>\n    <main>\n      <h1>Sign in</h1>\n      <form action=\"/sign-in\" method=\"post\">\n        <p>\n          <label for=\"signin-email\">Email</label>\n          <input id=\"signin-email\" name=\"email\" type=\"email\" required autocomplete=\"email\" />\n        </p>\n        <p>\n          <label for=\"signin-password\">Password</label>\n          <input\n            id=\"signin-password\"\n            name=\"password\"\n            type=\"password\"\n            required\n            autocomplete=\"current-password\"\n          />\n        </p>\n        <p><button type=\"submit\">Sign in</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-028",
        },
    },
    {
        "id": "seed-html-029",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 head with a canonical link element and a descriptive page title for a documentation article.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <link rel=\"canonical\" href=\"https://example.com/docs/authentication\" />\n    <title>Authentication overview — Docs</title>\n  </head>\n  <body>\n    <main>\n      <h1>Authentication overview</h1>\n    </main>\n  </body>\n</html>",
        "tags": ["metadata", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-029",
        },
    },
    {
        "id": "seed-html-030",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form error summary using role=\"alert\" listing two validation messages for missing required fields.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Form errors</title>\n  </head>\n  <body>\n    <main>\n      <h1>Create account</h1>\n      <div role=\"alert\">\n        <h2>Please fix the following errors</h2>\n        <ul>\n          <li>Email is required.</li>\n          <li>Password must be at least 12 characters.</li>\n        </ul>\n      </div>\n      <form action=\"/register\" method=\"post\">\n        <p>\n          <label for=\"register-email\">Email</label>\n          <input id=\"register-email\" name=\"email\" type=\"email\" required />\n        </p>\n        <p>\n          <label for=\"register-password\">Password</label>\n          <input id=\"register-password\" name=\"password\" type=\"password\" required minlength=\"12\" />\n        </p>\n        <p><button type=\"submit\">Create account</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["accessibility", "forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-030",
        },
    },
    {
        "id": "seed-html-031",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 definition list with three term-definition pairs explaining API concepts: Endpoint, Payload, and Rate limit.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>API glossary</title>\n  </head>\n  <body>\n    <dl>\n      <dt>Endpoint</dt>\n      <dd>A URL path that accepts HTTP requests for a specific resource.</dd>\n      <dt>Payload</dt>\n      <dd>The request or response body sent between client and server.</dd>\n      <dt>Rate limit</dt>\n      <dd>The maximum number of requests allowed within a time window.</dd>\n    </dl>\n  </body>\n</html>",
        "tags": ["semantic", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-031",
        },
    },
    {
        "id": "seed-html-032",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form with a date input for selecting a subscription renewal date. Include min and max attributes spanning one calendar year.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Renewal date</title>\n  </head>\n  <body>\n    <form action=\"/billing/renewal\" method=\"post\">\n      <label for=\"renewal-date\">Renewal date</label>\n      <input\n        id=\"renewal-date\"\n        name=\"renewalDate\"\n        type=\"date\"\n        min=\"2026-01-01\"\n        max=\"2026-12-31\"\n        required\n      />\n      <p><button type=\"submit\">Schedule renewal</button></p>\n    </form>\n  </body>\n</html>",
        "tags": ["forms", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-032",
        },
    },
    {
        "id": "seed-html-033",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 nav landmark marking the current page with aria-current=\"page\" on the active link among three sibling links.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Account navigation</title>\n  </head>\n  <body>\n    <nav aria-label=\"Account sections\">\n      <ul>\n        <li><a href=\"/account/profile\">Profile</a></li>\n        <li><a href=\"/account/security\" aria-current=\"page\">Security</a></li>\n        <li><a href=\"/account/billing\">Billing</a></li>\n      </ul>\n    </nav>\n  </body>\n</html>",
        "tags": ["accessibility", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-033",
        },
    },
    {
        "id": "seed-html-034",
        "targetLanguage": "HTML",
        "instruction": "Write a multi-section HTML5 registration form with two fieldsets: Account details (email, password) and Organization (company name, role). Each fieldset has a legend.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Registration form</title>\n  </head>\n  <body>\n    <main>\n      <h1>Register</h1>\n      <form action=\"/register\" method=\"post\">\n        <fieldset>\n          <legend>Account details</legend>\n          <p>\n            <label for=\"reg-email\">Email</label>\n            <input id=\"reg-email\" name=\"email\" type=\"email\" required autocomplete=\"email\" />\n          </p>\n          <p>\n            <label for=\"reg-password\">Password</label>\n            <input id=\"reg-password\" name=\"password\" type=\"password\" required minlength=\"12\" />\n          </p>\n        </fieldset>\n        <fieldset>\n          <legend>Organization</legend>\n          <p>\n            <label for=\"reg-company\">Company name</label>\n            <input id=\"reg-company\" name=\"company\" type=\"text\" required autocomplete=\"organization\" />\n          </p>\n          <p>\n            <label for=\"reg-role\">Role</label>\n            <input id=\"reg-role\" name=\"role\" type=\"text\" required autocomplete=\"organization-title\" />\n          </p>\n        </fieldset>\n        <p><button type=\"submit\">Create account</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "accessibility", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-034",
        },
    },
    {
        "id": "seed-html-035",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 article page with nested sections for Overview, Requirements, and Rollout plan. Maintain a logical heading hierarchy from h1 through h3.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Feature proposal</title>\n  </head>\n  <body>\n    <article>\n      <header>\n        <h1>Self-service billing exports</h1>\n        <p>Proposal for finance and operations teams.</p>\n      </header>\n      <section>\n        <h2>Overview</h2>\n        <p>Customers can download CSV invoices without contacting support.</p>\n      </section>\n      <section>\n        <h2>Requirements</h2>\n        <h3>Access control</h3>\n        <p>Only billing admins may export historical invoices.</p>\n        <h3>Audit trail</h3>\n        <p>Each export event is logged with user and timestamp.</p>\n      </section>\n      <section>\n        <h2>Rollout plan</h2>\n        <p>Pilot with ten enterprise accounts before general availability.</p>\n      </section>\n    </article>\n  </body>\n</html>",
        "tags": ["semantic", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-035",
        },
    },
    {
        "id": "seed-html-036",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 search form inside a search landmark with role=\"search\", a labeled query input, and a submit button.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Knowledge base search</title>\n  </head>\n  <body>\n    <header>\n      <h1>Knowledge base</h1>\n      <search role=\"search\" aria-label=\"Knowledge base search\">\n        <form action=\"/kb/search\" method=\"get\">\n          <label for=\"kb-query\">Search articles</label>\n          <input id=\"kb-query\" name=\"q\" type=\"search\" required />\n          <button type=\"submit\">Search</button>\n        </form>\n      </search>\n    </header>\n    <main>\n      <p>Find answers across onboarding, billing, and security topics.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "layout", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-036",
        },
    },
    {
        "id": "seed-html-037",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 data table for a quarterly report with row headers, column headers, a caption, and scope attributes on all th elements.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Quarterly report table</title>\n  </head>\n  <body>\n    <table>\n      <caption>2026 quarterly performance summary</caption>\n      <thead>\n        <tr>\n          <th scope=\"col\">Quarter</th>\n          <th scope=\"col\">Active users</th>\n          <th scope=\"col\">Churn rate</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <th scope=\"row\">Q1</th>\n          <td>12,400</td>\n          <td>2.1%</td>\n        </tr>\n        <tr>\n          <th scope=\"row\">Q2</th>\n          <td>13,050</td>\n          <td>1.8%</td>\n        </tr>\n        <tr>\n          <th scope=\"row\">Q3</th>\n          <td>13,900</td>\n          <td>1.6%</td>\n        </tr>\n      </tbody>\n    </table>\n  </body>\n</html>",
        "tags": ["tables", "accessibility", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-037",
        },
    },
    {
        "id": "seed-html-038",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form where each required input uses aria-describedby to link helper text. Include fields for username and API token.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>API credentials form</title>\n  </head>\n  <body>\n    <main>\n      <h1>API credentials</h1>\n      <form action=\"/settings/api\" method=\"post\">\n        <p>\n          <label for=\"api-username\">Username</label>\n          <input id=\"api-username\" name=\"username\" type=\"text\" required aria-describedby=\"username-help\" />\n          <span id=\"username-help\">Use the service account name shown in the admin console.</span>\n        </p>\n        <p>\n          <label for=\"api-token\">API token</label>\n          <input id=\"api-token\" name=\"token\" type=\"text\" required aria-describedby=\"token-help\" />\n          <span id=\"token-help\">Paste the token generated during provisioning.</span>\n        </p>\n        <p><button type=\"submit\">Save credentials</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "accessibility", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-038",
        },
    },
    {
        "id": "seed-html-039",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page combining header, nav, main, aside, and footer landmarks. Each landmark must contain identifiable heading text.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Full landmark page</title>\n  </head>\n  <body>\n    <header>\n      <h1>Operations console</h1>\n    </header>\n    <nav aria-label=\"Primary\">\n      <h2>Primary navigation</h2>\n      <ul>\n        <li><a href=\"/overview\">Overview</a></li>\n        <li><a href=\"/incidents\">Incidents</a></li>\n      </ul>\n    </nav>\n    <main>\n      <h2>Incident queue</h2>\n      <p>No active incidents.</p>\n    </main>\n    <aside aria-label=\"Runbook links\">\n      <h2>Runbooks</h2>\n      <ul>\n        <li><a href=\"/runbooks/db-failover\">Database failover</a></li>\n        <li><a href=\"/runbooks/cache-purge\">Cache purge</a></li>\n      </ul>\n    </aside>\n    <footer>\n      <h2>Support</h2>\n      <p>Contact on-call via pager rotation.</p>\n    </footer>\n  </body>\n</html>",
        "tags": ["layout", "semantic", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-039",
        },
    },
    {
        "id": "seed-html-040",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 file upload form accepting a single PDF document. Restrict the input with accept=\"application/pdf\" and include helper text.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Document upload</title>\n  </head>\n  <body>\n    <main>\n      <h1>Upload contract</h1>\n      <form action=\"/contracts/upload\" method=\"post\" enctype=\"multipart/form-data\">\n        <p>\n          <label for=\"contract-file\">PDF document</label>\n          <input id=\"contract-file\" name=\"contract\" type=\"file\" accept=\"application/pdf\" required />\n        </p>\n        <p>Only unsigned PDF files up to 10 MB are accepted.</p>\n        <p><button type=\"submit\">Upload</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-040",
        },
    },
    {
        "id": "seed-html-041",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 table using colspan and rowspan to merge header cells for a two-level column heading over monthly metrics.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Metrics matrix</title>\n  </head>\n  <body>\n    <table>\n      <caption>Monthly metrics by team</caption>\n      <thead>\n        <tr>\n          <th rowspan=\"2\" scope=\"col\">Team</th>\n          <th colspan=\"2\" scope=\"colgroup\">May</th>\n          <th colspan=\"2\" scope=\"colgroup\">June</th>\n        </tr>\n        <tr>\n          <th scope=\"col\">Tickets closed</th>\n          <th scope=\"col\">CSAT</th>\n          <th scope=\"col\">Tickets closed</th>\n          <th scope=\"col\">CSAT</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <th scope=\"row\">Support</th>\n          <td>420</td>\n          <td>4.6</td>\n          <td>455</td>\n          <td>4.7</td>\n        </tr>\n        <tr>\n          <th scope=\"row\">Success</th>\n          <td>310</td>\n          <td>4.8</td>\n          <td>328</td>\n          <td>4.9</td>\n        </tr>\n      </tbody>\n    </table>\n  </body>\n</html>",
        "tags": ["tables", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-041",
        },
    },
    {
        "id": "seed-html-042",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 head combining charset, viewport, description, canonical link, and a referrer policy meta tag.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta name=\"description\" content=\"Release notes for version 5.0 of the analytics platform.\" />\n    <link rel=\"canonical\" href=\"https://example.com/releases/5-0\" />\n    <meta name=\"referrer\" content=\"strict-origin-when-cross-origin\" />\n    <title>Analytics 5.0 release notes</title>\n  </head>\n  <body>\n    <main>\n      <h1>Analytics 5.0 release notes</h1>\n    </main>\n  </body>\n</html>",
        "tags": ["metadata", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-042",
        },
    },
    {
        "id": "seed-html-043",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 figure with an img, figcaption, and a linked long description via aria-describedby on the image.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Architecture diagram</title>\n  </head>\n  <body>\n    <figure>\n      <img\n        id=\"arch-diagram\"\n        src=\"/assets/diagrams/request-flow.png\"\n        alt=\"Request flow diagram\"\n        aria-describedby=\"arch-diagram-desc\"\n        width=\"800\"\n        height=\"450\"\n      />\n      <figcaption>High-level request flow across gateway, services, and datastore.</figcaption>\n      <p id=\"arch-diagram-desc\">\n        Requests enter through the API gateway, route to auth and billing services, then persist\n        events in the audit datastore.\n      </p>\n    </figure>\n  </body>\n</html>",
        "tags": ["media", "accessibility", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-043",
        },
    },
    {
        "id": "seed-html-044",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 form with a datalist providing suggested values for a company size field while still allowing free text entry.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Company profile</title>\n  </head>\n  <body>\n    <form action=\"/profile/company\" method=\"post\">\n      <label for=\"company-size\">Company size</label>\n      <input id=\"company-size\" name=\"companySize\" type=\"text\" list=\"company-size-options\" required />\n      <datalist id=\"company-size-options\">\n        <option value=\"1-10 employees\"></option>\n        <option value=\"11-50 employees\"></option>\n        <option value=\"51-200 employees\"></option>\n        <option value=\"201-1000 employees\"></option>\n      </datalist>\n      <p><button type=\"submit\">Save profile</button></p>\n    </form>\n  </body>\n</html>",
        "tags": ["forms", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-044",
        },
    },
    {
        "id": "seed-html-045",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a breadcrumb nav using an ordered list. Mark the current page as the final list item without a link.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Invoice detail</title>\n  </head>\n  <body>\n    <nav aria-label=\"Breadcrumb\">\n      <ol>\n        <li><a href=\"/billing\">Billing</a></li>\n        <li><a href=\"/billing/invoices\">Invoices</a></li>\n        <li aria-current=\"page\">Invoice 1042</li>\n      </ol>\n    </nav>\n    <main>\n      <h1>Invoice 1042</h1>\n      <p>Issued June 1, 2026.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["semantic", "accessibility", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-045",
        },
    },
    {
        "id": "seed-html-046",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 checkout form where each required field links validation hints via aria-describedby and marks invalid fields with aria-invalid=\"true\".",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Checkout validation</title>\n  </head>\n  <body>\n    <main>\n      <h1>Checkout</h1>\n      <form action=\"/checkout\" method=\"post\">\n        <p>\n          <label for=\"ship-name\">Full name</label>\n          <input\n            id=\"ship-name\"\n            name=\"fullName\"\n            type=\"text\"\n            required\n            aria-invalid=\"true\"\n            aria-describedby=\"ship-name-error ship-name-help\"\n          />\n          <span id=\"ship-name-help\">Enter the recipient name as it appears on the shipping label.</span>\n          <span id=\"ship-name-error\" role=\"alert\">Full name is required.</span>\n        </p>\n        <p>\n          <label for=\"ship-postal\">Postal code</label>\n          <input\n            id=\"ship-postal\"\n            name=\"postalCode\"\n            type=\"text\"\n            required\n            aria-invalid=\"true\"\n            aria-describedby=\"ship-postal-error\"\n          />\n          <span id=\"ship-postal-error\" role=\"alert\">Postal code must be five digits.</span>\n        </p>\n        <p><button type=\"submit\">Place order</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "accessibility", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-046",
        },
    },
    {
        "id": "seed-html-047",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 multi-step enrollment form structured as three numbered sections with hidden fieldsets for Personal, Plan, and Review steps. Use semantic section headings only.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Enrollment wizard markup</title>\n  </head>\n  <body>\n    <main>\n      <h1>Enroll in Analytics Pro</h1>\n      <form action=\"/enroll\" method=\"post\">\n        <section aria-labelledby=\"step-personal\">\n          <h2 id=\"step-personal\">Step 1 — Personal details</h2>\n          <fieldset>\n            <legend>Contact information</legend>\n            <label for=\"enroll-name\">Full name</label>\n            <input id=\"enroll-name\" name=\"fullName\" type=\"text\" required autocomplete=\"name\" />\n            <label for=\"enroll-email\">Work email</label>\n            <input id=\"enroll-email\" name=\"email\" type=\"email\" required autocomplete=\"email\" />\n          </fieldset>\n        </section>\n        <section aria-labelledby=\"step-plan\">\n          <h2 id=\"step-plan\">Step 2 — Plan selection</h2>\n          <fieldset>\n            <legend>Billing plan</legend>\n            <label><input type=\"radio\" name=\"plan\" value=\"monthly\" checked /> Monthly</label>\n            <label><input type=\"radio\" name=\"plan\" value=\"annual\" /> Annual</label>\n          </fieldset>\n        </section>\n        <section aria-labelledby=\"step-review\">\n          <h2 id=\"step-review\">Step 3 — Review</h2>\n          <p>Confirm your details before submitting enrollment.</p>\n        </section>\n        <p><button type=\"submit\">Submit enrollment</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "semantic", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-047",
        },
    },
    {
        "id": "seed-html-048",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 complex data table for a budget matrix with row and column headers, a tfoot summary row, and scope attributes throughout.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Budget matrix</title>\n  </head>\n  <body>\n    <table>\n      <caption>Department budget allocation for FY2026</caption>\n      <thead>\n        <tr>\n          <th scope=\"col\">Department</th>\n          <th scope=\"col\">Personnel</th>\n          <th scope=\"col\">Infrastructure</th>\n          <th scope=\"col\">Training</th>\n          <th scope=\"col\">Total</th>\n        </tr>\n      </thead>\n      <tbody>\n        <tr>\n          <th scope=\"row\">Engineering</th>\n          <td>$820,000</td>\n          <td>$140,000</td>\n          <td>$35,000</td>\n          <td>$995,000</td>\n        </tr>\n        <tr>\n          <th scope=\"row\">Support</th>\n          <td>$410,000</td>\n          <td>$25,000</td>\n          <td>$18,000</td>\n          <td>$453,000</td>\n        </tr>\n      </tbody>\n      <tfoot>\n        <tr>\n          <th scope=\"row\">Grand total</th>\n          <td>$1,230,000</td>\n          <td>$165,000</td>\n          <td>$53,000</td>\n          <td>$1,448,000</td>\n        </tr>\n      </tfoot>\n    </table>\n  </body>\n</html>",
        "tags": ["tables", "accessibility", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-048",
        },
    },
    {
        "id": "seed-html-049",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 page with a nav landmark where each link uses aria-current=\"page\" on the active item and aria-label on the nav for screen readers.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Docs navigation</title>\n  </head>\n  <body>\n    <nav aria-label=\"Documentation sections\">\n      <ul>\n        <li><a href=\"/docs/getting-started\">Getting started</a></li>\n        <li><a href=\"/docs/authentication\" aria-current=\"page\">Authentication</a></li>\n        <li><a href=\"/docs/webhooks\">Webhooks</a></li>\n        <li><a href=\"/docs/rate-limits\">Rate limits</a></li>\n      </ul>\n    </nav>\n    <main>\n      <h1>Authentication</h1>\n      <p>Use OAuth 2.0 client credentials for server-to-server integrations.</p>\n    </main>\n  </body>\n</html>",
        "tags": ["accessibility", "layout", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-049",
        },
    },
    {
        "id": "seed-html-050",
        "targetLanguage": "HTML",
        "instruction": "Write an HTML5 enterprise settings form combining text, email, number, select, checkbox, and textarea controls with required attributes and linked helper text via aria-describedby.",
        "code": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <title>Enterprise settings</title>\n  </head>\n  <body>\n    <main>\n      <h1>Enterprise settings</h1>\n      <form action=\"/settings/enterprise\" method=\"post\">\n        <fieldset>\n          <legend>Organization profile</legend>\n          <p>\n            <label for=\"org-name\">Organization name</label>\n            <input id=\"org-name\" name=\"organizationName\" type=\"text\" required aria-describedby=\"org-name-help\" />\n            <span id=\"org-name-help\">Displayed on invoices and audit exports.</span>\n          </p>\n          <p>\n            <label for=\"org-email\">Billing email</label>\n            <input id=\"org-email\" name=\"billingEmail\" type=\"email\" required autocomplete=\"email\" />\n          </p>\n          <p>\n            <label for=\"org-seats\">Licensed seats</label>\n            <input id=\"org-seats\" name=\"seatCount\" type=\"number\" min=\"1\" max=\"5000\" required />\n          </p>\n          <p>\n            <label for=\"org-region\">Primary region</label>\n            <select id=\"org-region\" name=\"region\" required>\n              <option value=\"\">Select a region</option>\n              <option value=\"us-east\">US East</option>\n              <option value=\"eu-west\">EU West</option>\n            </select>\n          </p>\n          <p>\n            <label>\n              <input type=\"checkbox\" name=\"ssoEnabled\" value=\"true\" />\n              Enable single sign-on\n            </label>\n          </p>\n          <p>\n            <label for=\"org-notes\">Internal notes</label>\n            <textarea id=\"org-notes\" name=\"notes\" rows=\"4\" aria-describedby=\"org-notes-help\"></textarea>\n            <span id=\"org-notes-help\">Optional context for your account team.</span>\n          </p>\n        </fieldset>\n        <p><button type=\"submit\">Save settings</button></p>\n      </form>\n    </main>\n  </body>\n</html>",
        "tags": ["forms", "accessibility", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: HTML-050",
        },
    },
]
