"""Gold seed catalog — JavaScript (Stage 2). 50 manually-authored GoldSeedExample dicts."""

JAVASCRIPT_SEEDS: list[dict] = [
    {
        "id": "seed-js-001",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `pluckNumbers`, which maps an array to its numeric elements only, preserving order. Non-number values are skipped. Throw a TypeError when the argument is not an array.",
        "code": "/**\n * Collect numeric values from an array.\n * @param {unknown[]} values\n * @returns {number[]}\n * @throws {TypeError} When values is not an array\n */\nexport function pluckNumbers(values) {\n  if (!Array.isArray(values)) {\n    throw new TypeError('values must be an array');\n  }\n\n  const result = [];\n  for (const value of values) {\n    if (typeof value === 'number' && !Number.isNaN(value)) {\n      result.push(value);\n    }\n  }\n  return result;\n}",
        "tags": ["array", "functional", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-001",
        },
    },
    {
        "id": "seed-js-002",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `sumValues`, which reduces an array of numbers to their total. An empty array returns 0. Throw a TypeError when the argument is not an array or contains non-numbers.",
        "code": "/**\n * Sum numeric values in an array.\n * @param {number[]} values\n * @returns {number}\n * @throws {TypeError} When values is invalid\n */\nexport function sumValues(values) {\n  if (!Array.isArray(values)) {\n    throw new TypeError('values must be an array');\n  }\n\n  let total = 0;\n  for (const value of values) {\n    if (typeof value !== 'number' || Number.isNaN(value)) {\n      throw new TypeError('each item must be a number');\n    }\n    total += value;\n  }\n  return total;\n}",
        "tags": ["array", "functional", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-002",
        },
    },
    {
        "id": "seed-js-003",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `groupByKey`, which groups an array of objects into a plain object keyed by a given property name. Missing keys are grouped under the string 'undefined'. Throw a TypeError when the first argument is not an array.",
        "code": "/**\n * Group records by a property value.\n * @param {Record<string, unknown>[]} records\n * @param {string} key\n * @returns {Record<string, Record<string, unknown>[]>}\n * @throws {TypeError} When records is not an array\n */\nexport function groupByKey(records, key) {\n  if (!Array.isArray(records)) {\n    throw new TypeError('records must be an array');\n  }\n\n  const grouped = {};\n  for (const record of records) {\n    const bucketKey = String(record?.[key]);\n    if (!grouped[bucketKey]) {\n      grouped[bucketKey] = [];\n    }\n    grouped[bucketKey].push(record);\n  }\n  return grouped;\n}",
        "tags": ["array", "functional", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-003",
        },
    },
    {
        "id": "seed-js-004",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `uniqueByKey`, which returns a new array keeping the first object for each distinct property value. Throw a TypeError when the items argument is not an array.",
        "code": "/**\n * Keep the first record per distinct key value.\n * @param {Record<string, unknown>[]} items\n * @param {string} key\n * @returns {Record<string, unknown>[]}\n * @throws {TypeError} When items is not an array\n */\nexport function uniqueByKey(items, key) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n\n  const seen = new Set();\n  const result = [];\n  for (const item of items) {\n    const value = item?.[key];\n    if (seen.has(value)) {\n      continue;\n    }\n    seen.add(value);\n    result.push(item);\n  }\n  return result;\n}",
        "tags": ["array", "functional", "module", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-004",
        },
    },
    {
        "id": "seed-js-005",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `deepMerge`, which recursively merges plain objects. Arrays and non-objects are replaced by the source value. Throw a TypeError when either argument is not a plain object.",
        "code": "/**\n * @param {unknown} value\n * @returns {boolean}\n */\nfunction isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n/**\n * Deep merge plain objects.\n * @param {Record<string, unknown>} target\n * @param {Record<string, unknown>} source\n * @returns {Record<string, unknown>}\n * @throws {TypeError} When arguments are not plain objects\n */\nexport function deepMerge(target, source) {\n  if (!isPlainObject(target) || !isPlainObject(source)) {\n    throw new TypeError('target and source must be plain objects');\n  }\n\n  const merged = { ...target };\n  for (const [key, value] of Object.entries(source)) {\n    const existing = merged[key];\n    if (isPlainObject(existing) && isPlainObject(value)) {\n      merged[key] = deepMerge(existing, value);\n    } else {\n      merged[key] = value;\n    }\n  }\n  return merged;\n}",
        "tags": ["object", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-005",
        },
    },
    {
        "id": "seed-js-006",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `pickKeys` and `omitKeys`. `pickKeys` returns a new object with only the listed keys. `omitKeys` returns a new object excluding the listed keys. Throw a TypeError when the source is not a plain object.",
        "code": "/**\n * @param {unknown} value\n * @returns {boolean}\n */\nfunction isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n/**\n * Copy selected keys from a plain object.\n * @param {Record<string, unknown>} source\n * @param {string[]} keys\n * @returns {Record<string, unknown>}\n * @throws {TypeError} When source is not a plain object\n */\nexport function pickKeys(source, keys) {\n  if (!isPlainObject(source)) {\n    throw new TypeError('source must be a plain object');\n  }\n  const picked = {};\n  for (const key of keys) {\n    if (key in source) {\n      picked[key] = source[key];\n    }\n  }\n  return picked;\n}\n\n/**\n * Copy a plain object excluding listed keys.\n * @param {Record<string, unknown>} source\n * @param {string[]} keys\n * @returns {Record<string, unknown>}\n * @throws {TypeError} When source is not a plain object\n */\nexport function omitKeys(source, keys) {\n  if (!isPlainObject(source)) {\n    throw new TypeError('source must be a plain object');\n  }\n  const omitted = { ...source };\n  for (const key of keys) {\n    delete omitted[key];\n  }\n  return omitted;\n}",
        "tags": ["object", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-006",
        },
    },
    {
        "id": "seed-js-007",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `isValidEmail`, which returns true when a string matches a basic email pattern (local@domain.tld) without spaces. Non-strings return false.",
        "code": "/**\n * Validate a basic email address format.\n * @param {unknown} value\n * @returns {boolean}\n */\nexport function isValidEmail(value) {\n  if (typeof value !== 'string') {\n    return false;\n  }\n  const trimmed = value.trim();\n  if (!trimmed) {\n    return false;\n  }\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(trimmed);\n}",
        "tags": ["validation", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-007",
        },
    },
    {
        "id": "seed-js-008",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `validateRequiredFields`, which checks a plain object against a list of required field names and returns an array of missing field names. Throw a TypeError when the record is not a plain object.",
        "code": "/**\n * @param {unknown} value\n * @returns {boolean}\n */\nfunction isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n/**\n * List required field names that are missing or empty.\n * @param {Record<string, unknown>} record\n * @param {string[]} requiredFields\n * @returns {string[]}\n * @throws {TypeError} When record is not a plain object\n */\nexport function validateRequiredFields(record, requiredFields) {\n  if (!isPlainObject(record)) {\n    throw new TypeError('record must be a plain object');\n  }\n\n  const missing = [];\n  for (const field of requiredFields) {\n    const value = record[field];\n    if (value === undefined || value === null || value === '') {\n      missing.push(field);\n    }\n  }\n  return missing;\n}",
        "tags": ["validation", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-008",
        },
    },
    {
        "id": "seed-js-009",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `fetchJsonWithTimeout`, which fetches a URL, parses JSON, and rejects on non-OK responses or timeouts. Map failures to Error instances with readable messages.",
        "code": "/**\n * Fetch JSON with a timeout and normalized errors.\n * @param {string} url\n * @param {number} timeoutMs\n * @returns {Promise<unknown>}\n */\nexport async function fetchJsonWithTimeout(url, timeoutMs = 5000) {\n  const timeoutPromise = new Promise((_, reject) => {\n    setTimeout(() => reject(new Error(`Request timed out after ${timeoutMs}ms`)), timeoutMs);\n  });\n\n  try {\n    const response = await Promise.race([fetch(url), timeoutPromise]);\n    if (!(response instanceof Response)) {\n      throw new Error('Request failed');\n    }\n    if (!response.ok) {\n      throw new Error(`Request failed with status ${response.status}`);\n    }\n    return await response.json();\n  } catch (error) {\n    if (error instanceof Error) {\n      throw error;\n    }\n    throw new Error('Request failed');\n  }\n}",
        "tags": ["async", "error-handling", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-009",
        },
    },
    {
        "id": "seed-js-010",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `fetchWithRetry`, which retries an async fetch function with exponential backoff until success or max attempts. Return the final result or throw the last error.",
        "code": "/**\n * Retry an async operation with exponential backoff.\n * @param {() => Promise<unknown>} operation\n * @param {{ maxAttempts?: number, baseDelayMs?: number }} options\n * @returns {Promise<unknown>}\n */\nexport async function fetchWithRetry(operation, options = {}) {\n  const maxAttempts = options.maxAttempts ?? 3;\n  const baseDelayMs = options.baseDelayMs ?? 200;\n  let attempt = 0;\n  let lastError;\n\n  while (attempt < maxAttempts) {\n    try {\n      return await operation();\n    } catch (error) {\n      lastError = error instanceof Error ? error : new Error(String(error));\n      attempt += 1;\n      if (attempt >= maxAttempts) {\n        break;\n      }\n      const delay = baseDelayMs * 2 ** (attempt - 1);\n      await new Promise((resolve) => setTimeout(resolve, delay));\n    }\n  }\n\n  throw lastError ?? new Error('Operation failed');\n}",
        "tags": ["async", "error-handling", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-010",
        },
    },
    {
        "id": "seed-js-011",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `toggleClass`, which adds or removes a CSS class on an element based on a force flag. When force is omitted, the class is toggled. Return whether the class is present after the operation.",
        "code": "/**\n * Toggle a class on a DOM element.\n * @param {Element} element\n * @param {string} className\n * @param {boolean} [force]\n * @returns {boolean}\n */\nexport function toggleClass(element, className, force) {\n  if (force === undefined) {\n    return element.classList.toggle(className);\n  }\n  return element.classList.toggle(className, force);\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-011",
        },
    },
    {
        "id": "seed-js-012",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `createFragmentFromHtml`, which parses an HTML template string into a DocumentFragment using a template element. Throw a TypeError when markup is not a string.",
        "code": "/**\n * Parse HTML markup into a DocumentFragment safely via <template>.\n * @param {string} markup\n * @returns {DocumentFragment}\n * @throws {TypeError} When markup is not a string\n */\nexport function createFragmentFromHtml(markup) {\n  if (typeof markup !== 'string') {\n    throw new TypeError('markup must be a string');\n  }\n\n  const template = document.createElement('template');\n  template.innerHTML = markup.trim();\n  return template.content;\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-012",
        },
    },
    {
        "id": "seed-js-013",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `delegateClicks`, which listens for clicks on a container and invokes a callback when the event target matches a selector. Return a cleanup function that removes the listener.",
        "code": "/**\n * Delegate click events from a container to matching descendants.\n * @param {Element} container\n * @param {string} selector\n * @param {(target: Element, event: MouseEvent) => void} callback\n * @returns {() => void}\n */\nexport function delegateClicks(container, selector, callback) {\n  const listener = (event) => {\n    const target = event.target;\n    if (!(target instanceof Element)) {\n      return;\n    }\n    const match = target.closest(selector);\n    if (!match || !container.contains(match)) {\n      return;\n    }\n    callback(match, event);\n  };\n\n  container.addEventListener('click', listener);\n  return () => container.removeEventListener('click', listener);\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-013",
        },
    },
    {
        "id": "seed-js-014",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module with named exports `clamp`, `minOf`, and `maxOf` for numeric bounds. `clamp` constrains a number between min and max inclusive. Throw a TypeError when any argument is not a number.",
        "code": "/**\n * Constrain a number within inclusive bounds.\n * @param {number} value\n * @param {number} min\n * @param {number} max\n * @returns {number}\n * @throws {TypeError} When arguments are not numbers\n */\nexport function clamp(value, min, max) {\n  if (typeof value !== 'number' || typeof min !== 'number' || typeof max !== 'number') {\n    throw new TypeError('value, min, and max must be numbers');\n  }\n  return Math.min(max, Math.max(min, value));\n}\n\n/**\n * @param {number} a\n * @param {number} b\n * @returns {number}\n * @throws {TypeError} When arguments are not numbers\n */\nexport function minOf(a, b) {\n  if (typeof a !== 'number' || typeof b !== 'number') {\n    throw new TypeError('arguments must be numbers');\n  }\n  return Math.min(a, b);\n}\n\n/**\n * @param {number} a\n * @param {number} b\n * @returns {number}\n * @throws {TypeError} When arguments are not numbers\n */\nexport function maxOf(a, b) {\n  if (typeof a !== 'number' || typeof b !== 'number') {\n    throw new TypeError('arguments must be numbers');\n  }\n  return Math.max(a, b);\n}",
        "tags": ["module", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-014",
        },
    },
    {
        "id": "seed-js-015",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `pipe` and `compose`, which combine unary functions. `pipe` applies functions left-to-right; `compose` applies them right-to-left.",
        "code": "/**\n * Pipe unary functions from left to right.\n * @param {...(value: unknown) => unknown} functions\n * @returns {(value: unknown) => unknown}\n */\nexport function pipe(...functions) {\n  return (value) => {\n    let current = value;\n    for (const fn of functions) {\n      current = fn(current);\n    }\n    return current;\n  };\n}\n\n/**\n * Compose unary functions from right to left.\n * @param {...(value: unknown) => unknown} functions\n * @returns {(value: unknown) => unknown}\n */\nexport function compose(...functions) {\n  return (value) => {\n    let current = value;\n    for (let index = functions.length - 1; index >= 0; index -= 1) {\n      current = functions[index](current);\n    }\n    return current;\n  };\n}",
        "tags": ["module", "functional", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-015",
        },
    },
    {
        "id": "seed-js-016",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports a `CurrencyAmount` class storing minor units (integer cents) and currency code. The constructor throws when cents is not an integer or currency is not a three-letter string.",
        "code": "/**\n * Immutable currency amount in minor units.\n */\nexport class CurrencyAmount {\n  /** @type {number} */\n  #cents;\n\n  /** @type {string} */\n  #currency;\n\n  /**\n   * @param {number} cents\n   * @param {string} currency\n   */\n  constructor(cents, currency) {\n    if (!Number.isInteger(cents)) {\n      throw new TypeError('cents must be an integer');\n    }\n    if (typeof currency !== 'string' || !/^[A-Z]{3}$/.test(currency)) {\n      throw new TypeError('currency must be a three-letter code');\n    }\n    this.#cents = cents;\n    this.#currency = currency;\n  }\n\n  /** @returns {number} */\n  get cents() {\n    return this.#cents;\n  }\n\n  /** @returns {string} */\n  get currency() {\n    return this.#currency;\n  }\n\n  /**\n   * @param {CurrencyAmount} other\n   * @returns {CurrencyAmount}\n   */\n  add(other) {\n    if (other.currency !== this.#currency) {\n      throw new Error('currency mismatch');\n    }\n    return new CurrencyAmount(this.#cents + other.cents, this.#currency);\n  }\n}",
        "tags": ["class", "error-handling", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-016",
        },
    },
    {
        "id": "seed-js-017",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports an immutable `Stack` class with `push`, `pop`, `peek`, and `size`. `push` returns a new stack. `pop` returns the top value and a new stack without it. `pop` and `peek` throw when the stack is empty.",
        "code": "/**\n * Immutable LIFO stack.\n */\nexport class Stack {\n  /** @type {unknown[]} */\n  #items;\n\n  /** @param {unknown[]} [items] */\n  constructor(items = []) {\n    this.#items = [...items];\n  }\n\n  /** @param {unknown} value */\n  push(value) {\n    return new Stack([...this.#items, value]);\n  }\n\n  /**\n   * @returns {{ value: unknown, stack: Stack }}\n   */\n  pop() {\n    if (this.#items.length === 0) {\n      throw new Error('stack is empty');\n    }\n    const value = this.#items[this.#items.length - 1];\n    const stack = new Stack(this.#items.slice(0, -1));\n    return { value, stack };\n  }\n\n  /** @returns {unknown} */\n  peek() {\n    if (this.#items.length === 0) {\n      throw new Error('stack is empty');\n    }\n    return this.#items[this.#items.length - 1];\n  }\n\n  /** @returns {number} */\n  size() {\n    return this.#items.length;\n  }\n}",
        "tags": ["class", "module", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-017",
        },
    },
    {
        "id": "seed-js-018",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `debounce`, which delays invoking a function until after wait milliseconds have elapsed since the last call. Return a debounced function with a `cancel` method.",
        "code": "/**\n * Debounce a function call.\n * @param {(value: unknown) => void} fn\n * @param {number} waitMs\n * @returns {{ call: (value: unknown) => void, cancel: () => void }}\n */\nexport function debounce(fn, waitMs) {\n  let timerId;\n\n  const cancel = () => {\n    if (timerId !== undefined) {\n      clearTimeout(timerId);\n      timerId = undefined;\n    }\n  };\n\n  const call = (value) => {\n    cancel();\n    timerId = setTimeout(() => {\n      timerId = undefined;\n      fn(value);\n    }, waitMs);\n  };\n\n  return { call, cancel };\n}",
        "tags": ["functional", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-018",
        },
    },
    {
        "id": "seed-js-019",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `memoize`, which caches results of a unary function keyed by the first argument using a Map. Only the first argument is used as the cache key.",
        "code": "/**\n * Memoize a unary function by first argument.\n * @param {(value: unknown) => unknown} fn\n * @returns {(value: unknown) => unknown}\n */\nexport function memoize(fn) {\n  const cache = new Map();\n\n  return (value) => {\n    if (cache.has(value)) {\n      return cache.get(value);\n    }\n    const result = fn(value);\n    cache.set(value, result);\n    return result;\n  };\n}",
        "tags": ["functional", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-019",
        },
    },
    {
        "id": "seed-js-020",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `parseCsvLine`, which splits a single CSV line into fields, supporting quoted fields with escaped double quotes. Throw a TypeError when the line is not a string.",
        "code": "/**\n * Parse one CSV line into fields.\n * @param {string} line\n * @returns {string[]}\n * @throws {TypeError} When line is not a string\n */\nexport function parseCsvLine(line) {\n  if (typeof line !== 'string') {\n    throw new TypeError('line must be a string');\n  }\n\n  const fields = [];\n  let current = '';\n  let inQuotes = false;\n\n  for (let index = 0; index < line.length; index += 1) {\n    const char = line[index];\n    if (char === '\"') {\n      if (inQuotes && line[index + 1] === '\"') {\n        current += '\"';\n        index += 1;\n      } else {\n        inQuotes = !inQuotes;\n      }\n      continue;\n    }\n    if (char === ',' && !inQuotes) {\n      fields.push(current);\n      current = '';\n      continue;\n    }\n    current += char;\n  }\n\n  fields.push(current);\n  return fields;\n}",
        "tags": ["error-handling", "validation", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-020",
        },
    },
    {
        "id": "seed-js-021",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `runTasksWithLimit`, which runs async task functions with a maximum concurrency limit and returns results in original order. Tasks receive their index as an argument.",
        "code": "/**\n * Run async tasks with bounded concurrency.\n * @param {((index: number) => Promise<unknown>)[]} tasks\n * @param {number} limit\n * @returns {Promise<unknown[]>}\n */\nexport async function runTasksWithLimit(tasks, limit) {\n  const results = new Array(tasks.length);\n  let nextIndex = 0;\n\n  async function worker() {\n    while (nextIndex < tasks.length) {\n      const current = nextIndex;\n      nextIndex += 1;\n      results[current] = await tasks[current](current);\n    }\n  }\n\n  const workers = Array.from({ length: Math.min(limit, tasks.length) }, () => worker());\n  await Promise.all(workers);\n  return results;\n}",
        "tags": ["async", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-021",
        },
    },
    {
        "id": "seed-js-022",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `attachFieldValidator`, which validates a form field on change and toggles an error class plus aria-invalid on the control. The validator returns an error message string or null when valid.",
        "code": "/**\n * Attach live validation feedback to a form control.\n * @param {HTMLElement} field\n * @param {(value: string) => string | null} validator\n * @param {string} errorClass\n * @returns {() => void}\n */\nexport function attachFieldValidator(field, validator, errorClass = 'is-invalid') {\n  const runValidation = () => {\n    const value = 'value' in field ? String(field.value) : '';\n    const message = validator(value);\n    const isValid = message === null;\n    field.classList.toggle(errorClass, !isValid);\n    field.setAttribute('aria-invalid', isValid ? 'false' : 'true');\n    return message;\n  };\n\n  const listener = () => runValidation();\n  field.addEventListener('change', listener);\n  runValidation();\n  return () => field.removeEventListener('change', listener);\n}",
        "tags": ["dom", "validation", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-022",
        },
    },
    {
        "id": "seed-js-023",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `chunkArray`, which splits an array into sub-arrays of a given size. The last chunk may be smaller. Throw a TypeError when the array is invalid or size is not a positive integer.",
        "code": "/**\n * Split an array into fixed-size chunks.\n * @param {unknown[]} items\n * @param {number} size\n * @returns {unknown[][]}\n * @throws {TypeError} When arguments are invalid\n */\nexport function chunkArray(items, size) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  if (!Number.isInteger(size) || size <= 0) {\n    throw new TypeError('size must be a positive integer');\n  }\n\n  const chunks = [];\n  for (let index = 0; index < items.length; index += size) {\n    chunks.push(items.slice(index, index + size));\n  }\n  return chunks;\n}",
        "tags": ["array", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-023",
        },
    },
    {
        "id": "seed-js-024",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `flattenToDotKeys`, which flattens a nested plain object into dot-separated keys. Arrays are copied as leaf values, not recursed into.",
        "code": "/**\n * @param {unknown} value\n * @returns {boolean}\n */\nfunction isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n/**\n * Flatten nested plain objects to dot keys.\n * @param {Record<string, unknown>} source\n * @param {string} [prefix]\n * @returns {Record<string, unknown>}\n */\nexport function flattenToDotKeys(source, prefix = '') {\n  const flat = {};\n\n  for (const [key, value] of Object.entries(source)) {\n    const path = prefix ? `${prefix}.${key}` : key;\n    if (isPlainObject(value)) {\n      const nested = flattenToDotKeys(value, path);\n      Object.assign(flat, nested);\n    } else {\n      flat[path] = value;\n    }\n  }\n\n  return flat;\n}",
        "tags": ["object", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-024",
        },
    },
    {
        "id": "seed-js-025",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `ok`, `err`, and `unwrap`, implementing a lightweight Result type. `ok` and `err` create success or failure results. `unwrap` returns the value or throws the stored error.",
        "code": "/**\n * @typedef {{ ok: true, value: unknown } | { ok: false, error: Error }} Result\n */\n\n/**\n * @param {unknown} value\n * @returns {Result}\n */\nexport function ok(value) {\n  return { ok: true, value };\n}\n\n/**\n * @param {string | Error} error\n * @returns {Result}\n */\nexport function err(error) {\n  const failure = error instanceof Error ? error : new Error(error);\n  return { ok: false, error: failure };\n}\n\n/**\n * @param {Result} result\n * @returns {unknown}\n */\nexport function unwrap(result) {\n  if (result.ok) {\n    return result.value;\n  }\n  throw result.error;\n}",
        "tags": ["functional", "error-handling", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-025",
        },
    },
    {
        "id": "seed-js-026",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `firstElement` and `lastElement`, which return the first and last item of an array or undefined when empty. Throw a TypeError when the argument is not an array.",
        "code": "/**\n * @param {unknown[]} items\n * @returns {unknown | undefined}\n * @throws {TypeError} When items is not an array\n */\nexport function firstElement(items) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  return items.length === 0 ? undefined : items[0];\n}\n\n/**\n * @param {unknown[]} items\n * @returns {unknown | undefined}\n * @throws {TypeError} When items is not an array\n */\nexport function lastElement(items) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  return items.length === 0 ? undefined : items[items.length - 1];\n}",
        "tags": ["array", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-026",
        },
    },
    {
        "id": "seed-js-027",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `isPlainObject`, which returns true only for non-null objects that are not arrays. Export as the sole named export.",
        "code": "/**\n * Detect plain objects (not arrays or null).\n * @param {unknown} value\n * @returns {boolean}\n */\nexport function isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}",
        "tags": ["object", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-027",
        },
    },
    {
        "id": "seed-js-028",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `identity` and `constant`, unary helpers that return the argument or a fixed value respectively.",
        "code": "/**\n * Return the argument unchanged.\n * @param {unknown} value\n * @returns {unknown}\n */\nexport function identity(value) {\n  return value;\n}\n\n/**\n * Return a function that always yields the same value.\n * @param {unknown} value\n * @returns {() => unknown}\n */\nexport function constant(value) {\n  return () => value;\n}",
        "tags": ["functional", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-028",
        },
    },
    {
        "id": "seed-js-029",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `isNonEmptyString`, which returns true when the value is a string with non-whitespace content.",
        "code": "/**\n * Check for a non-empty trimmed string.\n * @param {unknown} value\n * @returns {boolean}\n */\nexport function isNonEmptyString(value) {\n  return typeof value === 'string' && value.trim().length > 0;\n}",
        "tags": ["validation", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-029",
        },
    },
    {
        "id": "seed-js-030",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `compact`, which returns a new array omitting null and undefined entries. Throw a TypeError when the argument is not an array.",
        "code": "/**\n * Remove null and undefined from an array.\n * @param {unknown[]} items\n * @returns {unknown[]}\n * @throws {TypeError} When items is not an array\n */\nexport function compact(items) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  return items.filter((item) => item !== null && item !== undefined);\n}",
        "tags": ["array", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-030",
        },
    },
    {
        "id": "seed-js-031",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `getPath`, which reads a nested property from an object using a dot-separated path string. Return undefined when any segment is missing.",
        "code": "/**\n * Read a nested property via dot path.\n * @param {Record<string, unknown>} source\n * @param {string} path\n * @returns {unknown}\n */\nexport function getPath(source, path) {\n  const segments = path.split('.');\n  let current = source;\n  for (const segment of segments) {\n    if (current === null || typeof current !== 'object') {\n      return undefined;\n    }\n    current = current[segment];\n  }\n  return current;\n}",
        "tags": ["object", "L1-trivial"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-031",
        },
    },
    {
        "id": "seed-js-032",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `zipArrays`, which pairs elements from two arrays into tuples. The result length matches the shorter array. Throw a TypeError when either argument is not an array.",
        "code": "/**\n * Zip two arrays into tuple pairs.\n * @param {unknown[]} left\n * @param {unknown[]} right\n * @returns {unknown[][]}\n * @throws {TypeError} When arguments are not arrays\n */\nexport function zipArrays(left, right) {\n  if (!Array.isArray(left) || !Array.isArray(right)) {\n    throw new TypeError('left and right must be arrays');\n  }\n  const length = Math.min(left.length, right.length);\n  const pairs = [];\n  for (let index = 0; index < length; index += 1) {\n    pairs.push([left[index], right[index]]);\n  }\n  return pairs;\n}",
        "tags": ["array", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-032",
        },
    },
    {
        "id": "seed-js-033",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `arrayDifference`, which returns values present in the first array but not the second, preserving first-array order without duplicates.",
        "code": "/**\n * Values in left not present in right.\n * @param {unknown[]} left\n * @param {unknown[]} right\n * @returns {unknown[]}\n * @throws {TypeError} When arguments are not arrays\n */\nexport function arrayDifference(left, right) {\n  if (!Array.isArray(left) || !Array.isArray(right)) {\n    throw new TypeError('left and right must be arrays');\n  }\n  const exclude = new Set(right);\n  const result = [];\n  const seen = new Set();\n  for (const value of left) {\n    if (exclude.has(value) || seen.has(value)) {\n      continue;\n    }\n    seen.add(value);\n    result.push(value);\n  }\n  return result;\n}",
        "tags": ["array", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-033",
        },
    },
    {
        "id": "seed-js-034",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `shallowEqual`, which compares two plain values for shallow equality. Objects compare own enumerable keys and values; arrays compare elements at each index.",
        "code": "/**\n * Shallow equality for objects and arrays.\n * @param {unknown} left\n * @param {unknown} right\n * @returns {boolean}\n */\nexport function shallowEqual(left, right) {\n  if (left === right) {\n    return true;\n  }\n  if (typeof left !== 'object' || typeof right !== 'object' || left === null || right === null) {\n    return false;\n  }\n  if (Array.isArray(left) && Array.isArray(right)) {\n    if (left.length !== right.length) {\n      return false;\n    }\n    for (let index = 0; index < left.length; index += 1) {\n      if (left[index] !== right[index]) {\n        return false;\n      }\n    }\n    return true;\n  }\n  if (Array.isArray(left) || Array.isArray(right)) {\n    return false;\n  }\n  const leftKeys = Object.keys(left);\n  const rightKeys = Object.keys(right);\n  if (leftKeys.length !== rightKeys.length) {\n    return false;\n  }\n  for (const key of leftKeys) {\n    if (left[key] !== right[key]) {\n      return false;\n    }\n  }\n  return true;\n}",
        "tags": ["object", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-034",
        },
    },
    {
        "id": "seed-js-035",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `isValidUrl`, which returns true for http or https URLs with a host. Non-strings and malformed URLs return false.",
        "code": "/**\n * Validate an http(s) URL string.\n * @param {unknown} value\n * @returns {boolean}\n */\nexport function isValidUrl(value) {\n  if (typeof value !== 'string') {\n    return false;\n  }\n  try {\n    const parsed = new URL(value);\n    return (parsed.protocol === 'http:' || parsed.protocol === 'https:') && parsed.hostname.length > 0;\n  } catch {\n    return false;\n  }\n}",
        "tags": ["validation", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-035",
        },
    },
    {
        "id": "seed-js-036",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `isValidPhoneDigits`, which returns true when a string contains only digits and optional leading plus, with length between 7 and 15.",
        "code": "/**\n * Basic digit-only phone validation.\n * @param {unknown} value\n * @returns {boolean}\n */\nexport function isValidPhoneDigits(value) {\n  if (typeof value !== 'string') {\n    return false;\n  }\n  const trimmed = value.trim();\n  if (!trimmed) {\n    return false;\n  }\n  const digits = trimmed.startsWith('+') ? trimmed.slice(1) : trimmed;\n  if (!/^[0-9]+$/.test(digits)) {\n    return false;\n  }\n  return digits.length >= 7 && digits.length <= 15;\n}",
        "tags": ["validation", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-036",
        },
    },
    {
        "id": "seed-js-037",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `delay`, which returns a Promise that resolves after the given number of milliseconds with an optional value.",
        "code": "/**\n * Resolve after a delay with an optional value.\n * @param {number} ms\n * @param {unknown} [value]\n * @returns {Promise<unknown>}\n */\nexport function delay(ms, value) {\n  return new Promise((resolve) => {\n    setTimeout(() => resolve(value), ms);\n  });\n}",
        "tags": ["async", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-037",
        },
    },
    {
        "id": "seed-js-038",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `withTimeout`, which wraps a Promise and rejects when it does not settle within the given milliseconds.",
        "code": "/**\n * Reject a promise when it exceeds a timeout.\n * @param {Promise<unknown>} promise\n * @param {number} timeoutMs\n * @returns {Promise<unknown>}\n */\nexport function withTimeout(promise, timeoutMs) {\n  return new Promise((resolve, reject) => {\n    const timer = setTimeout(() => {\n      reject(new Error(`Timed out after ${timeoutMs}ms`));\n    }, timeoutMs);\n\n    promise\n      .then((value) => {\n        clearTimeout(timer);\n        resolve(value);\n      })\n      .catch((error) => {\n        clearTimeout(timer);\n        reject(error);\n      });\n  });\n}",
        "tags": ["async", "error-handling", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-038",
        },
    },
    {
        "id": "seed-js-039",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `mapElements`, which queries all elements matching a selector within a root and maps them through a callback. Return an array of callback results.",
        "code": "/**\n * Map over elements matching a selector.\n * @param {ParentNode} root\n * @param {string} selector\n * @param {(element: Element, index: number) => unknown} callback\n * @returns {unknown[]}\n */\nexport function mapElements(root, selector, callback) {\n  const nodes = root.querySelectorAll(selector);\n  const results = [];\n  nodes.forEach((element, index) => {\n    results.push(callback(element, index));\n  });\n  return results;\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-039",
        },
    },
    {
        "id": "seed-js-040",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `setText`, which sets textContent on an element, clearing children when the text is empty. Throw a TypeError when the element is invalid.",
        "code": "/**\n * Set text content on an element safely.\n * @param {Element} element\n * @param {string} text\n * @throws {TypeError} When element is not an Element\n */\nexport function setText(element, text) {\n  if (!(element instanceof Element)) {\n    throw new TypeError('element must be an Element');\n  }\n  element.textContent = text;\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-040",
        },
    },
    {
        "id": "seed-js-041",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `showElement` and `hideElement`, which toggle the hidden attribute on an element. Hidden elements have the hidden attribute set; visible elements have it removed.",
        "code": "/**\n * Show an element by removing the hidden attribute.\n * @param {HTMLElement} element\n */\nexport function showElement(element) {\n  element.hidden = false;\n  element.removeAttribute('hidden');\n}\n\n/**\n * Hide an element using the hidden attribute.\n * @param {HTMLElement} element\n */\nexport function hideElement(element) {\n  element.hidden = true;\n  element.setAttribute('hidden', '');\n}",
        "tags": ["dom", "L2-standard"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-041",
        },
    },
    {
        "id": "seed-js-042",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports a `ListenerList` class with `on` to add named listeners and `notify` to invoke all listeners with a payload. `off` removes a listener by name.",
        "code": "/**\n * Named listener registry for simple pub/sub.\n */\nexport class ListenerList {\n  /** @type {Map<string, (payload: unknown) => void>} */\n  #listeners = new Map();\n\n  /**\n   * @param {string} name\n   * @param {(payload: unknown) => void} listener\n   */\n  on(name, listener) {\n    this.#listeners.set(name, listener);\n  }\n\n  /**\n   * @param {string} name\n   */\n  off(name) {\n    this.#listeners.delete(name);\n  }\n\n  /**\n   * @param {unknown} payload\n   */\n  notify(payload) {\n    for (const listener of this.#listeners.values()) {\n      listener(payload);\n    }\n  }\n}",
        "tags": ["module", "class", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-042",
        },
    },
    {
        "id": "seed-js-043",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `throttle`, which invokes a function at most once per wait period. Return an object with `call` and `cancel` methods.",
        "code": "/**\n * Throttle a function to once per interval.\n * @param {(value: unknown) => void} fn\n * @param {number} waitMs\n * @returns {{ call: (value: unknown) => void, cancel: () => void }}\n */\nexport function throttle(fn, waitMs) {\n  let timerId;\n  let lastValue;\n\n  const cancel = () => {\n    if (timerId !== undefined) {\n      clearTimeout(timerId);\n      timerId = undefined;\n    }\n  };\n\n  const call = (value) => {\n    lastValue = value;\n    if (timerId !== undefined) {\n      return;\n    }\n    fn(lastValue);\n    timerId = setTimeout(() => {\n      timerId = undefined;\n    }, waitMs);\n  };\n\n  return { call, cancel };\n}",
        "tags": ["functional", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-043",
        },
    },
    {
        "id": "seed-js-044",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `once`, which wraps a function so it executes only on the first invocation. Subsequent calls return the first result without calling the function again.",
        "code": "/**\n * Invoke a function only once.\n * @param {() => unknown} fn\n * @returns {() => unknown}\n */\nexport function once(fn) {\n  let called = false;\n  let stored;\n\n  return () => {\n    if (!called) {\n      stored = fn();\n      called = true;\n    }\n    return stored;\n  };\n}",
        "tags": ["functional", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-044",
        },
    },
    {
        "id": "seed-js-045",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `sortByKey`, which returns a new array sorted by a property name. Sorting is stable for equal keys. Throw a TypeError when items is not an array.",
        "code": "/**\n * Stable sort objects by a property key.\n * @param {Record<string, unknown>[]} items\n * @param {string} key\n * @returns {Record<string, unknown>[]}\n * @throws {TypeError} When items is not an array\n */\nexport function sortByKey(items, key) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  return items\n    .map((item, index) => ({ item, index }))\n    .sort((left, right) => {\n      const leftValue = left.item?.[key];\n      const rightValue = right.item?.[key];\n      if (leftValue === rightValue) {\n        return left.index - right.index;\n      }\n      if (leftValue === undefined) {\n        return 1;\n      }\n      if (rightValue === undefined) {\n        return -1;\n      }\n      if (typeof leftValue === 'string' && typeof rightValue === 'string') {\n        return leftValue.localeCompare(rightValue);\n      }\n      return leftValue < rightValue ? -1 : 1;\n    })\n    .map((row) => row.item);\n}",
        "tags": ["array", "functional", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-045",
        },
    },
    {
        "id": "seed-js-046",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `invertObject`, which swaps keys and values of a plain object with stringifiable values. Duplicate values become arrays of keys in the result.",
        "code": "/**\n * @param {unknown} value\n * @returns {boolean}\n */\nfunction isPlainObject(value) {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n/**\n * Invert object keys and values.\n * @param {Record<string, unknown>} source\n * @returns {Record<string, unknown>}\n * @throws {TypeError} When source is not a plain object\n */\nexport function invertObject(source) {\n  if (!isPlainObject(source)) {\n    throw new TypeError('source must be a plain object');\n  }\n\n  const inverted = {};\n  for (const [key, value] of Object.entries(source)) {\n    const invertedKey = String(value);\n    const existing = inverted[invertedKey];\n    if (existing === undefined) {\n      inverted[invertedKey] = key;\n    } else if (Array.isArray(existing)) {\n      existing.push(key);\n    } else {\n      inverted[invertedKey] = [existing, key];\n    }\n  }\n  return inverted;\n}",
        "tags": ["object", "functional", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-046",
        },
    },
    {
        "id": "seed-js-047",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `mapAsync`, which applies an async mapper to each array item sequentially and returns all results in order.",
        "code": "/**\n * Map an array with an async function sequentially.\n * @param {unknown[]} items\n * @param {(item: unknown, index: number) => Promise<unknown>} mapper\n * @returns {Promise<unknown[]>}\n * @throws {TypeError} When items is not an array\n */\nexport async function mapAsync(items, mapper) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  const results = [];\n  for (let index = 0; index < items.length; index += 1) {\n    results.push(await mapper(items[index], index));\n  }\n  return results;\n}",
        "tags": ["async", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-047",
        },
    },
    {
        "id": "seed-js-048",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports a `DisclosureWidget` class that toggles visibility of a panel when a button is clicked, updating aria-expanded on the button.",
        "code": "/**\n * Toggle a disclosure panel with aria-expanded state.\n */\nexport class DisclosureWidget {\n  /** @type {HTMLButtonElement} */\n  #button;\n\n  /** @type {HTMLElement} */\n  #panel;\n\n  /**\n   * @param {HTMLButtonElement} button\n   * @param {HTMLElement} panel\n   */\n  constructor(button, panel) {\n    this.#button = button;\n    this.#panel = panel;\n    this.#button.setAttribute('aria-expanded', 'false');\n    this.#panel.hidden = true;\n  }\n\n  /** Toggle panel visibility. */\n  toggle() {\n    const expanded = this.#button.getAttribute('aria-expanded') === 'true';\n    const next = !expanded;\n    this.#button.setAttribute('aria-expanded', String(next));\n    this.#panel.hidden = !next;\n  }\n\n  /** Attach click listener on the button. */\n  bind() {\n    this.#button.addEventListener('click', () => this.toggle());\n  }\n}",
        "tags": ["dom", "class", "L3-composite"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-048",
        },
    },
    {
        "id": "seed-js-049",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `parseJsonSafe`, which parses JSON and returns a Result-style object with `ok` true and `value`, or `ok` false and `error` as an Error. Never throws.",
        "code": "/**\n * @typedef {{ ok: true, value: unknown } | { ok: false, error: Error }} SafeResult\n */\n\n/**\n * Parse JSON without throwing.\n * @param {string} text\n * @returns {SafeResult}\n */\nexport function parseJsonSafe(text) {\n  try {\n    return { ok: true, value: JSON.parse(text) };\n  } catch (error) {\n    const failure = error instanceof Error ? error : new Error(String(error));\n    return { ok: false, error: failure };\n  }\n}",
        "tags": ["functional", "error-handling", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-049",
        },
    },
    {
        "id": "seed-js-050",
        "targetLanguage": "JavaScript",
        "instruction": "Write an ES module that exports `partition`, which splits an array into two arrays based on a predicate: `[passing, failing]`. Throw a TypeError when items is not an array.",
        "code": "/**\n * Split an array by a predicate.\n * @param {unknown[]} items\n * @param {(item: unknown, index: number) => boolean} predicate\n * @returns {[unknown[], unknown[]]}\n * @throws {TypeError} When items is not an array\n */\nexport function partition(items, predicate) {\n  if (!Array.isArray(items)) {\n    throw new TypeError('items must be an array');\n  }\n  const passing = [];\n  const failing = [];\n  for (let index = 0; index < items.length; index += 1) {\n    const item = items[index];\n    if (predicate(item, index)) {\n      passing.push(item);\n    } else {\n      failing.push(item);\n    }\n  }\n  return [passing, failing];\n}",
        "tags": ["array", "error-handling", "L4-edge-case"],
        "metadata": {
            "author": "pipeline-operator",
            "created": "2026-06-20",
            "source": "manual",
            "notes": "topic: JS-050",
        },
    },
]
